const std = @import("std");
const print = std.debug.print;

pub fn main() void {
    const start = std.time.microTimestamp();

    var total_price_part1: u32 = 0;
    var total_price_part2: u32 = 0;

    var visited: Visited = [_][COLUMNS]bool{[_]bool{false} ** COLUMNS} ** ROWS;

    for (0..ROWS) |y| {
        for (0..COLUMNS) |x| {
            if (visited[y][x]) continue;
            const price_part1, const price_part2 = RegionExplorer.explore(
                .{ .x = x, .y = y },
                &visited,
            );
            total_price_part1 += price_part1;
            total_price_part2 += price_part2;
        }
    }

    print("Total price part 1: {}\n", .{total_price_part1});
    print("Total price part 2: {}\n", .{total_price_part2});

    const end = std.time.microTimestamp();
    const micros = end - start;
    const millis = @as(f32, @floatFromInt(micros)) / 1000;
    std.debug.print("\nExecution time: {d:.3}ms\n", .{millis});
}

const Visited = [ROWS][COLUMNS]bool;

const RegionExplorer = struct {
    visited: *Visited,
    plot_type: u8,
    area: u32,
    perimeter: u32,
    corners: u32,

    fn explore(starting_plot: Plot, visited: *Visited) [2]u32 {
        const plot_type = starting_plot.getPlotType();
        var self = RegionExplorer{
            .visited = visited,
            .plot_type = plot_type,
            .area = 0,
            .perimeter = 0,
            .corners = 0,
        };
        self.visitPlot(starting_plot);
        return .{
            self.area * self.perimeter,
            self.area * self.corners,
        };
    }

    fn visitPlot(self: *RegionExplorer, plot: Plot) void {
        if (self.visited[plot.y][plot.x]) {
            return;
        }

        self.visited[plot.y][plot.x] = true;

        self.area += 1;
        self.corners += checkForCorners(plot);

        var neighbour_count: u32 = 0;
        const directions = [_]Direction{ .Left, .Up, .Right, .Down };
        for (directions) |direction| {
            const neighbour = plot.getAdjacant(direction) orelse continue;
            if (neighbour.getPlotType() != self.plot_type) {
                continue;
            }
            neighbour_count += 1;
            self.visitPlot(neighbour);
        }

        self.perimeter += 4 - neighbour_count;
    }

    fn checkForCorners(plot: Plot) u32 {
        var corners: u32 = 0;
        const plot_type = plot.getPlotType();

        const left = plot.getAdjacant(.Left);
        const up = plot.getAdjacant(.Up);
        const right = plot.getAdjacant(.Right);
        const down = plot.getAdjacant(.Down);

        const outer_corner_checks = [_][2]?Plot{
            .{ left, up },
            .{ up, right },
            .{ right, down },
            .{ down, left },
        };

        for (outer_corner_checks) |adjacent_plots| {
            const a_adj, const b_adj = adjacent_plots;

            const is_a_other = a_adj == null or a_adj.?.getPlotType() != plot_type;
            const is_b_other = b_adj == null or b_adj.?.getPlotType() != plot_type;

            if (is_a_other and is_b_other) {
                corners += 1;
            }
        }

        const up_left = plot.getAdjacant(.UpLeft);
        const up_right = plot.getAdjacant(.UpRight);
        const down_right = plot.getAdjacant(.DownRight);
        const down_left = plot.getAdjacant(.DownLeft);

        const inner_corner_checks = [_][3]?Plot{
            .{ left, up_left, up },
            .{ up, up_right, right },
            .{ right, down_right, down },
            .{ down, down_left, left },
        };

        for (inner_corner_checks) |adjacent_plots| {
            const a_adj, const diag, const b_adj = adjacent_plots;

            const is_a_same = a_adj != null and a_adj.?.getPlotType() == plot_type;
            const is_diag_other = diag != null and diag.?.getPlotType() != plot_type;
            const is_b_same = b_adj != null and b_adj.?.getPlotType() == plot_type;

            if (is_a_same and is_diag_other and is_b_same) {
                corners += 1;
            }
        }

        return corners;
    }
};

const Direction = enum { Left, UpLeft, Up, UpRight, Right, DownRight, Down, DownLeft };

const Plot = struct {
    x: usize,
    y: usize,

    fn toInputIdx(self: *const Plot) usize {
        return self.y * (COLUMNS + 1) + self.x;
    }

    fn getPlotType(self: *const Plot) u8 {
        return input[self.toInputIdx()];
    }

    fn getAdjacant(self: *const Plot, direction: Direction) ?Plot {
        switch (direction) {
            .Left => {
                if (self.x == 0) return null;
                return Plot{ .x = self.x - 1, .y = self.y };
            },
            .UpLeft => {
                if (self.x == 0 or self.y == 0) return null;
                return Plot{ .x = self.x - 1, .y = self.y - 1 };
            },
            .Up => {
                if (self.y == 0) return null;
                return Plot{ .x = self.x, .y = self.y - 1 };
            },
            .UpRight => {
                if (self.x + 1 == COLUMNS or self.y == 0) return null;
                return Plot{ .x = self.x + 1, .y = self.y - 1 };
            },
            .Right => {
                if (self.x + 1 == COLUMNS) return null;
                return Plot{ .x = self.x + 1, .y = self.y };
            },
            .DownRight => {
                if (self.x + 1 == COLUMNS or self.y + 1 == ROWS) return null;
                return Plot{ .x = self.x + 1, .y = self.y + 1 };
            },
            .Down => {
                if (self.y + 1 == ROWS) return null;
                return Plot{ .x = self.x, .y = self.y + 1 };
            },
            .DownLeft => {
                if (self.x == 0 or self.y + 1 == ROWS) return null;
                return Plot{ .x = self.x - 1, .y = self.y + 1 };
            },
        }
    }
};

const ROWS = blk: {
    @setEvalBranchQuota(30000);
    var rows: usize = 0;
    var row_iterator = std.mem.split(u8, input, "\n");
    while (row_iterator.next()) |_| {
        rows += 1;
    }
    break :blk rows;
};

const COLUMNS = blk: {
    var row_iterator = std.mem.split(u8, input, "\n");
    const row = row_iterator.next().?;
    break :blk row.len;
};

const input =
    \\RRRRJJKKKKKKKKKKKKKKKKKKKKKNEEEEEEEEEEEMMMMMMMMMMMMMMZZZZZZZZZZZUUUUUURXXXXXXXXXXXXDDDDDDQQQQQQQOPPPOOOOOXXXXXXXHHYHBBBSKKKKKLLLBBBBBBBBBJBC
    \\RRRRJKKKKKKKKKKKKKKKKKKKKKKNNEEEEEEEEEEMMMMMMMMMMMMMMZZZZZZZZZZZUUUUUUXXXXXXXXXXXXDDDDKKKKKKKPXVOOOOOOOOOXXXXXXXHHHHHSSKKKKKKBBBBBBBBBBBBBBC
    \\RRRRJJJKJKKKKKKKKKKKKKKKKKKNNEEEEEEEEEEEEMMMMMMMMMMZMZZZZZZZZZZUUUUUUUMMXXXXXXXXXXDDDKIKKKKKKKXXXXXOOOOXXXXXXXXXHHHHHHSKKKKKKPPHBBBBBBBBBBBC
    \\RRRRRRJKJKKKKKKKKVKKKKKKKKNNNEEEEEEEEEEEMMMMMMMMMMMZZZZZZZZZZZZUUUUUUUMMMXXXXXXXXXXXXKKKKKKKKXXXXXXSOOOOXXXXXXXXHHHHHHHKKKKKKPPPPBCBBBBBBBBZ
    \\RRRRRJJJJJJKKKKKKVKKKKKKKNNNNEEEEEEEEEEEDMMMMMMMMMMZZZZSSSZZZZZZUUUUUUUUXXXXXXXXXXXKKKKKKKKKKXXXXXXOOOOXXXXXXXHHHHHHHHSKKKKKKPCCCCCCBBBBEZZZ
    \\NNRRRJJJJKKKKKKVVVKKKKKKKNBNNNEEEEEEEEEDDMMMMMMMMMMMMMSSSZZZZZZZZUUUUUUKXXQXXXXXXXXKKKKKKKKKKXXXXXXXXOOXXXXXXXXHHHHHDSSKKKKKKPCACCCCBBZZZZZZ
    \\NRRRRHJJKKKKKVVVVVVKVKKKKNNNNEEEEEKKEEEDDDMMMMMMMSSSSMMSSZZZZZZZUUUUUUUUXXXXXXXXXXKKKKKKKKKKXXXXXXXXXXXXXXXXXXXHHHHHSSSKKKKKKPPPCCCCABZZZZZZ
    \\NNNNHHJKKKKKKKVVVVVVVVWWKNNMMMEEEKKEEBDDDDDMMMMMMSSSSSSSSSZZZZUUUUUUUUUUXXXXXXXXMMMMKKKKKKKKXXXXXXXXXXXXXXXXXXXHHHHHSSSSSSKKKPPOCCCCABZZZZZZ
    \\NNNNHHHHHHHHVVVVVVVVVWWWWWNMMMEEKKKKKDDDDDDMMMMSSSSSSSSSSQQZZUQQQUUUUUUUXOOXXXXMMMMMMMKKKKKKXXXXXXXXXXXXXXXXXXHHHHHHSSSSSSKKKPPOOOCCABZZZZZZ
    \\NNNNHHHHHHHHHVVVVVVVMWWWWWWWWMEEEEKKKDDDDDDDDMMMMSSSSSSSSQQZZUQUUUUUUUUUUUOMMXMMMMMMMMKKKKKXXXXXXXXXXXXXXXXXXXXXXHHSKKKKKKKKKKPPPOCHZZZZZZZZ
    \\NNNNNHHHHHHHHVVVVVVVVWWWWWWWWMEENNNKDDDDDDDSDDMMMLSSSSSSQQZZZUUUUUUUUUUUUUOMMMMMMMMMMMMKKKKXQQQXXXXXXAXXXXXXXXXXXXHSKKKKKKKKKKPPPOZZZZZZZZZZ
    \\NPNPHHHHHVVVVVVVVVVWWWWWWWWWWMEEENNNDDDDDDDDMMMMLLSSSSSSSQQQZQQUMUUUUUUUUUOMMMMMMMMMKKKKKKKKXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKPPPOOZZZZZZZZZ
    \\PPNPUUHHHVVVVVVVVVVVWWWWWWWWWWDDEDDDDDDDDDDDDDLLLLLSSSQQQQQQQQQUUUUUUUUUUUMMMMMMMMMMBBBBBRKKEEEEXXEXXXXXXXBXXBXXXXXXKKKKKKKKKKPPOOOZOOZRRRZZ
    \\PPPPPUUUUUVVVVVVVVVVWWWWWWWWWWXXAAUDDDDDDDDDDDLLLLLSQQQQQQQQQQUUUUUUUUUUUMMMMMMMMMMMBBBBBRKKEEEEXXEXXXXXXBBXXBXXXFXMKKKKKKKKKKPPOOOZOORRRRZZ
    \\PPPPUUUUUUUVVVVVVVVWWWWWWWWWWCXXAAUDDDDDDDDDDDLLLLLSQQQQQQQQQQUQUUUUNUUUMMMMMMGMMMMBBBBBBBBEEMMMMXXXXXXXXBBBBBFFEFFFMKKKPPPPPPOOOOOOOOORRRZZ
    \\PPPPUUUUUUUVVVVVVVVVWWWWQQQQQQQQUUUUDDDDDDDDDDDLLLSSQQQQQDDQQQQQUUNNNNNNNNNMMQBBBMBBBBBBBBBBEBBMMMMMMMMXXBBBBBFFFKKKKKKKVPPPPPOOOOOOOORRRRZS
    \\PPPPPUUUUUUUVVVVVVVWWWWWQQQQQQQQUUUUDDDDDDDDLDDLLLLLQQDQQDDDDDQQUUNNNNNNNNNMMQQBBBBBBBBBBBBEEBMMMMMMMMMXXBBBBBFFFKKKKKKKVVPPPPPOOOOOORRRRRSS
    \\PPPPPPUUUUUUVVVVTTTTNWWWQQQQQQQQUUUUDDDDDDDLLLDLLLLQQDDDQQDDDDDUUNNNNNNNNNNNNNNNBBBBBBBBBBBBBBMMMMMMMMMEBBBBBBFFKKKKEEEEVVVFPPOOOOOOORRRRRRS
    \\PPPPPPUUUUUUVVTTTTTTTWWWQQQQQQQQUUUDDDDDDDDLLLLLLLLQDDDDDDDDDDDDUUNNNNNNNNNNNNNNSBBBBBBBBBBBBBBMMMMMMMMEIBBBBFFFKKKFEEEEFFFFFFOOOOORRRRRRSSS
    \\PPPPPUUUTUTUTTTTTQQQQQQQQQQQQQQQUUUUSSSDDDSLSLLLLLLLLDDDDDDDDVDDAANNNNNNNNNNRRNNSBBBBBBBBBBBBBBMMMMMMMMIIIBTIFFFKKKFEEEEFFFFFFOOORRRRRRGGSSS
    \\PPPPPPTTTUTTTTTTTQQQQQQQQQQQQQQQUUFSSSSSSSSLSSLLLLLLLDDDDDDDDDDDJJNNQNNNNNNSSSSSSBBBBBBBBBBBBBMMMMMMMMMMIIIIIFQFFEEEEEEEEEEFVFFRRRRRRRRGGSSS
    \\PPPPPPYYTTTTTTTTTQQQQQQQQQQQQQQQUUFFSSSSSSLLSSSLLLLLLDDDDDDDDDDDJJJJNNNNNNNRSSSSYYBBBBBBBBFFBBMMMMMMMMMMIIIIIFFFFEEEEEEEEEEVVVVRRRRRRRRRGSSS
    \\PPPPPPJTTTTTTTTTTQQQQQQQQQQFFFFFFFFAAISSSSSSSSLLLLLLZDDDDDDDDDJYJJJJJJJNNSSSSSSSYBBBBBBBBBFFMBMMMMMMMMMMIIIIIFFFFEEEEEEEEEEVVVRRVRRRRRRRRSSS
    \\PPPJJJJJJJJTTTTTTQQQQQQQQQQFFFFFFFAAIIISSSSSSLLLLLLZZDDDDDDDDJJJJJJJJJJNSSSSSSSSSBBBBBBCCAMMMMMMMMMMMMMMMMIIIIFIIEEEEEEEEEEEEEERVRRRRRRFRSSS
    \\PPPJJJJJJJTTTTTTTQQQQQQQQQQFFFFFAAAAAAASSSSSSLLLLLZZZZZDDDDDJJJJJJJJJJJJJSSSSSSSSSVBBBBCCMMCCUMMMMXXMMMMMMIIIIIIIEEEEEEEEEEEEEEVVVRRRRRRRUSS
    \\PPPJJJJJJJDTTTTTTQQQQQQQQQQFFFFAAAAAAAASSSSZZLLZLZZZEZDDDDSSSSJJJJJJJJJJJSSSSSSSSSVVBBCCCCCCCUMMMMXXXXXDDDIIIIIIGEEEEEEEEEEEEEEVVRRRRRRRRUUS
    \\PPMJJVJJJJJTTTTTTQQQQQQQQQQOOFFFAAAAAAAASZZZZZZZZZZEEEEDDDSSSSHHHJJJJJJJJSSSSSSSSSBBBBCCCCCCCCCXCCXXXDDHDIIIIIIIGEEEEEEEEEEEEEEUURURRRRRRUSS
    \\PMMMFMBBJJTTTTNNNNNNQQQQQQQOOFFAAAAAAAAAAZZZZZZZZZZZEEEEESSSHHHHHHJJJJJJSSSSSSSSSSSSBCCCCCCCCCCCCHXXXDHHHIIIIIIGGEEEEEEEEEEVVVUUUUUUURRRUUSS
    \\PMMMMMBBBTTTTTNNNNNNQQQQQQQOOAAAAAAAAAAAZZZDZZZZZEEEEEEEEHHHHHHHHHHJJJJSSSSSSSSSSSSSSCCCCCCCCCCCQXXYYHHHHHIIGGIGGEEEEEEEEEECCCCUCUUUURRUUUUU
    \\MMMMMMMBTTTTBBNNNNNNTOOOOOOOAAAAABAAAAAAZWZDDDDZZEEEEEEEEHHHHHHHHHHJJJJSSSSSSSSSSSSSSCCCCCCCCCCQQQHHHHHHHHIIGGGGGGGGGGGGCCCCCCCWCCCUURUUUUUU
    \\MMMMMMMMTTNNNNNNNNNNTOOOOOOOOAAAABABAAAAZWWDDDDDDEEEEEEEEHHHHHHHHHHOJJSSSSSSSSSSSSSSSCCCCCCCCCCQQQHHHHHHHHIIGGGGGGGGGGGCCCCCCCCCCCCUUUUUUUUU
    \\MMMMMMMMMTNNNNNNNNNNOOOOOOOOOARABBBBAXAPWWWDDDDDDOEEEEEEEHHHHHHHHHHHHHSSSSSSSSSSSSSSSSCCCCCCCCCJHHHHHHHHHHCIIGGGGGGGGGGCCCCCCCCCCCCUUUUUUUUU
    \\MMMMMMMMMMNNNNNNNNNNOOOOOOOOOOBZBBBBIBPPWWWWDDDDDOEEEEEEEEYHHRRRRRRHHHHSSSXXSSSSTTTSSSCCCCCCCCJJHHHHHHHHHCCIKGGGGGGGGGGGGCCCCCCCCCCCUUUUUUUU
    \\MMMMMMMMMMBBBBNNNNNNOOOOOOOOBBBBBBBBBBBBWWWWWDDDOOEEEEEEEHHHHRRRRRRHHHSSSSXXXHHTTTTTTSCTGCCCCJJJJHHHHHHHHCIIKKGGGGGGGGGCCCXXXXXXXCCUUUUUUUUU
    \\MMMMMMMMMXBBBBNNNNNNOOOOOOOBBBBBBBBBBLLLLWWWWDDDDOOOEEEEKKHHHRRRRRRHHHBBSXXXXHHTTTTTTSTTGGCTCJJJHHHHHHHHHHXMKKGGGGGGGGCCCCXXXXXXXXXXXXXXUUUU
    \\MMMMMMMMMXBBBBNNNNNNXOOOOOOBBBBBBBBBBBBLWWWWWDOOOOOOEEEEEKKRRRRRRRRHBBBBBBHXHHHHHHTTTTTGGCCCGJJHHHHHHHHHHHXMMMGGGGGGGCCCCCXXXXXXXXXXXXXXUUUU
    \\MMMMMMMMMMMBBBNNNNNNOOOOOBBBBBBBBBBBBLLLWWWWWBBOOOOOOOEEKKKRRRRRRRRHBBBBBHHHQHHHHHHTTTTGGGGGGGHHHHHHHHHHHHHMMMGGGGGGGCBCCCXXXXXXXXXXXXXXUUUQ
    \\MMMMMMMMMBBBBBBBBIIIIOOOOBBBBBBBBBBBBLLIWWWWBBBOOOOJJOEEEEERRRRRRRRRBHHHHHHHHHHHHHHTTTTGGGGGGHHHHHHHHHHHEEMMMMGGGGHGGTBBCCXXXXXXXXXXXXXXUUUQ
    \\MMMMMMMMMBBBBBBBIIIIDOODDMDBBBBBBBBBBWWWWWWBBBBBBBOJJJJIEEKRRRRRRRRRHHHHHHHHHHHHHTTTTTTGGGGGGGHHHTTTHHHHEEMMMGGGGGGGTTTBBCXXXXXXXXXXXXXXUUUQ
    \\MMMMMMMMMMMFBBBBBBBBDDKDDDDDBBBBBBBBBNBBBBBBBBBBBBJJJJJJJJKKKRRRRRRRRHHHHHHHHHHHHHHHTMMMGGGGGGHHTTOOHHHHHEMEEEGTTGGTIITTTCXXXXXXXXXXXXXXUUUQ
    \\MMMMMMGMGGGGQQBBBKEDDDDDDDDDDDNBBBBNBNNNNBBBBBBBQQJJJJJJJJKKRRRRRRRRRHHHHHHHHHHHHHMMMMMMMGGGGGGHTTOOHOOOEEEEEEETTGSTITTTTCXXXXXXXXXXXXXXUUUQ
    \\MMMMMMGGGGGGQQQQKKEDDDDDDDDDDDNBBBBNNNNNNBBBBBBBQQJJJJJJJKKRRRRRRRRRRHHHHHHHHHHHHHJHMMMMGGGGGGGOOOOOOOOOEOOEEEETTGGTTTTTTTXXXXXXXXXXXXXXUUUQ
    \\MMMMMMMKGKKGKKQKKKDDDDDDDDDDNNNNBBNNNNNNBBBBBBBBBBJJJJJJJKKRRRRRRRRRRNHHHUUHHHHHHHHHMMOOOOGGGGGOOOOOOOOOOBOOEOOTTGGTTTTTTTXXXXXXXBUUUMUUUUUQ
    \\DMMMMMMKKKKKKKKKKPDDDDDDDDDDDNNNNNNNNNNNNBBBBBBBBBBJJJJJJKKKRRRRRRRRRRNHHHHHFHHHHHHHHMMOOOGOOGGFOOOOOOOOOOOOOOOTTGGGTTTTTTTTHHZZUUTUUUUUUUUQ
    \\DMMMMMMKKKKKKKKKKPPDDDDDDDDDDDNNNNNNNNNNNBBBBBBBMBJJJJJJKKKRRRRRRRRRRPHHPPPHHDHHHHMMMMOOOOOOOOFFFOOOOOOOOOOOOOOOTTTTTTTTTTTTHHZHUUUUUUUUUUUU
    \\DDMMDDDKKKKKKKKKKKPPDDDDDDDPDNNNNNNNNNNNNNBBBBBMMJJJJJJJJJWRRRRRRRRRRPPPPPPPPHHHHHMMMOOOOOOOOOOOOOOOOOOOOOOOOOOTTTTTTTTTTTTTTHHHUUUUUUUUUUUU
    \\DDDDDDDKKKKKKKKKKKKDDDDDDDDDDNNNNNNNNNNNNNBBXMMMMJJOJJJJJWWRRJRRRRRRRPPPPPPPPPHHMMMMMMOOOOOOOOOOOOOOOOOOOOOOOOOOTTTTTTTTTTTTTHHHUHHUUUUUUUUU
    \\DDDDDDDDKKKKKKKKKKKKDDDDDDDDZZNNNNNNNNNNNNBBMMMMJJJOOJJJJWWWWRRRRRRRRRPPPPPPPPSMMMMMMOOOOOOOOOOOOOOOOOOOOOOOOZZTTTTTTTTTTTTTTHHHHHHUUUUUUUUU
    \\DDDDZZDDDKKKKKKKKKKKPDDDDDDDDZZZNNNGNNNNNNNNNOOOJJJOOLJUJJWWWRRRRRNRPRPPPPPPPPSSSSSSOOOOOOOOOOOOOOOOOOOOOOOOOVZTZZTTTTTTTTTTTTHHJJUUUUUUUUUU
    \\DDZZZZZZDDKKKKKKKKDPPDDDDDDDZZZZZNNNNNNNJNOOOOOOOOOOOOJWWWWWWWRRRRRRPPPPPPPPPSSSSSSKOOOOOOOOOOOOJOOHOOOOOZOOVVZZZZZZTTTTTJTTTTHHJJUUIUUUUUUU
    \\ZZZZZZZZZDKKKKKKKKDDDDDDDDSDZZZZNNNNNNNJJJOOOOOOOOOOOOOOWWWWWWRRWRRRPSPPPPPSSSSSSSSSSOOOOOOOOOOJJOOHOOOOOZZRZZZZZZZSSSSTSJTTZJHHHJJJJJURRUUU
    \\ZZZZZZZZZKKKKKKKKZZZDDDZZDDDDZZZFNNNNNNZJJOOOOOOOOOOOOOOOWWWWWWWWRRWSSSSSPPSSSSSSSSSSOOOOOOOOOOOBHHHOOOOOZZZZZZZZZZSSSSSSJJJJJHHJJJJJJURRRUU
    \\ZZZZZZZZZKKKKKKKKZZZZDZZZZZZZZZZZNNNNNZZJJAOOOOOOOOOOOOWWWWWWWWWWWRWSSGSPPSSSSSSSSSSSSOSOOOOOOOOBHBHOMMMZZZWWZZZZZZSSSSSSSJJJJJJJJJJJJRRRRUU
    \\ZZZZZZZZZKKIKKKKKZZZZZZZZZFFFFZZZZNNNNZZJJAAOOOOOOOOOOOWWWWWWWWWWWWWSSSSSPSSSSSSSSSSSSSSSOOBBBBBBBBHOMMMZZZZZZZZZZSSSSSSSSSJJJJJJJJJJJJRRRRU
    \\ZZZZZZZZRRRRKKKKKQZZZZZZZZFFFFFFDDDDDNZZJJOOOOOOOOOOOOOOWWWWWWWWWWWSSSSFSSSSSSSSSSSSSSSSBBOBBBBBBBBHOOMMOOEZZZZZSSSSSSSSSSJJJJJJJJJJJJRRRRAU
    \\ZZZZZZRZRRRRRRRRRRZZZZZZZFFFFFFFDDDDDDYYJYOOOOOOOOOOOOWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSUBBBBBBBBBBBBBOOOOCOOZZZZZSSSSSSSSSSJJJJJJJJJJJJRRRRAA
    \\ZZZZZZRRRRRRRRRRRRRZZZZZFFFFFFXFFFFFYYYYYYOOOOOOOOOOOGWWWWWWSWWWWWWWSSSSSSSSSSSSSSSSSUUBBBBBBBBBBBPBOOOOOOZZZZZZZZSSSSSSSJJJJJJJJJJJAJAAAAAA
    \\ZZZZZZRRRRRRRRRRRZZZZZZZFFFFFFFFFFFQQQYYYOOOYYYYOOOOOOOWWWSSSSWWWWWWSSSSSSDDSDSSOSSSSUUBBBBBBBBBBBPOOOOOONZZZZZZZZSSSSSSSJIJJJJJJJJJAAAAAAAU
    \\SZZZZZRRRRRRRRRCAZZZZOZFFFFFFFFFFFFQVVYYYYYOYYYYYOYYOOSWWWWSSYSWWWWWSSSISPDDDDSDDDUUUUUBBBBBBBBBBBOOOOOORZTZZZZZZSSSSSSSSJIJJJJJJJJJJAAAAAAA
    \\SSZZZSSRRRRRRRRAAOOOOOOOFFFFFFFFFFFQVVYYYYYYYYYYYYYYYYWWWWSSSSSSWWSWSSPIPPDDDDSDDDDDUUUUUBBBBBBBBBHOOOOORZZZZZZZZIISIISSSUIJJJJJJJJJJAAAAAAA
    \\SSSZSSSRRRRRRRRAAAOOOOFFFFFFFFFFFFQQVQQYYYYYYYYYYYYYYYCWWSSSSSSSWSSSSSPPPDDDDDDDDDDDBUUBBBBBBBBBBBOOOOOOOZZZZZZIZZIIIISIIIIJJJJJJJJJAAAAAAAA
    \\SSSSSSSRRRRRRRRRROOOOFFFFFFFFNFFFFQQQQQYYYYYYYYYYYYYYYCWSSSSSSSSWSSSSSPPPDDDDDDDXXXIBUBBBBBBBBBBBBPPPPTRRTZZZZIIZIIIIIIIIIIIIJJJJJJAAAAAAAAA
    \\SSSSSSSSRRRRRQQQQOOOOAAAAFFFFFFFDDDQQQQYYYYYYYYYYYYYYYYWDSSSSSSSSSSSPPPPPPPDDDDDDXXXBBBBBBBBBBBBBPPPPTTTTTZRZZZIIIIIIIIIIIIIJJJJJJNBBAAAAAAA
    \\SSSSRRRRRRRRRQQQQOOOAAAAAAAFFFFDDDDQQQYYYYYYYYYYYYYYYYUSSSSSSSSSSSSSPPPPPPPDDDDDDXXXBBBXBBBBBBBBBRRRTTTTTTTRZZZIIIIIIIIIIIIIIIJJNJNNAAAAAAAA
    \\SSSSRRRRRRRRRQQQQQQOAQQQQQFFFFDDDDQQYYYYYYYYYYYYYYYYYYUUUUUSSSSSSSPPMPPPPPPPYDDDXXXXXXXXXBCBBBSBSTTRRTTTTTTTTTIIIIIIIIIIIIIJJJJJNNNNNAAAAAAA
    \\TSSSRRRRRRRRRRRQQQQQQQQQQQFFFEEDDEQEYYSSSYYCCCYYYYYYYYUUUUSSSSSSSPPPPPPPPPPYYYYRXXXXXXXXXXXXXSSSSTTRRTTTTTTTTTTTTTNIIIIIIIIJJJJJNNNNNAAIAACC
    \\SSSSRRRRRRRRRRRQQQQQQQQQQQEEEEEDEEEEYESSSYDICCPUUYUYYCUUUUUUUSSSSPPPPPPPPPYYYYYRXXXXXXXXXXXXSSSSSTTTTTTTTTTTTTTTTTTIIINIIIJJJNNNNNNNNNANAACC
    \\HHHHHRHRRHHHHHRQQQQQQQQQAAAEEEEDDEEEEEEESSIIIEUUUUUYYYUUUUUUUUSSSPPPPPPPPPYYYYYRXYXXXXXXXXXXXXXXSTTTTTTTTTTTTTTTTVTIIIIIIIJWWNNNNNNNNNNNAACC
    \\HHHHHHHHHHHHHHHQQQQQQQQQAAAEEEEEEEEEEEESSSIIIIIZZUUUUUUVVVUUUSSJPPPPPPPPPPYYYYYRYYXXXXXXXXXXXSXSSSTTSSTTTTTTTTTTTTAAAIDDDDJWWNNNNNNNNNNNNAAA
    \\HHHHHHHHHHHHRRRRRAQQQQQQAAAAEEEEEEEEEEEEIIIIIIDIZZUUUUUVVVVVVSSJPPPPPPPPPPYYYYYYYYXXXXXXXXXSSSSSSSSSSSTTTTTTTTTTTTAAAAADHHJWWHHHNNNNNNNNNANB
    \\HHHHHHHHHHHRRRRRAAAAAAAAAAAAEEEEEEEEEEEGGIIIIIDIIIUUUUUVVVVVVBJJJJPPPIIBYYYYYYYYYYXXXXXXXXSSSSSSSSCCCSTTTTTTTTTTTTAAAAAAHHHHHHHHNNNNNNNNNLNB
    \\HHHHHHHHHHHHHHRRAAAAAAAAAAAEEEEEEEEEEEGGGIIIIIIIUHUUUUVVVVVVVBIJJJPXPIIYJYYYYYYYYYXXXXXXXXXXSSSSSSCCCCCCTTTTTTTTTTAAAAUHHHHHHHHHHHNNNNNNNNNB
    \\HHHHHHHHHHHHRHRAAAAAAAAAAXEEEEEEEEEEESDGGGGIIIIIUUUUUUVVVVVVVVIIJJPIPIIYYYYYYYYYYYXXXXXXXXXXSSSSEEECCCCCCCFTTTTTTTAAAAUHHHHHHHHHHHHNNNNNNNNN
    \\HHHHHHHHHHHRRRRRRAAAAAAAAEEEEEEEEESSSSDDSGGGIIIIGUULLUVVVVVVVVIIJPPIIIYYYYYYYYYYSSSSXXXXXXSSSSSSEEEEECCCCCCDTTTTUAAAAAHHHHHHHHHHHHHNMNNNNNNK
    \\HHHHHHHHHRRRRRRRRRAAAAAAAEEEEEESESSSSSSSSGGGIIGGGGGLLLVVVVVJMIIIIIIIIIYYYYYYYYYYSSSXXXSXSXXXSSSEEEEEECCCCTTTTTTTUAAAAJHHHHHHHHHHHHHMMTNNNNNN
    \\HHHHHHHHHRRRRRRARRAYYYKKAKEEEEESSSSSSSSSSSSGGGGGGGGGLLLLVJVJMIIIIIIIIIYYYYYYYYYSSSSSSSSSSSEESSEFEEEECCCCCZTTTTTTTAAAAJJHHHHHHHHMHMMMMMMNUNNU
    \\HHHHHHHHHRRRRRAARRAAAYKKKKKEEEKKSSSSSSSSSSGGGGGGGGGGLLLLLJJJMIIIIIIIIIIIIMYRYYYSSSSSSSSSSSEEEEEEEEEEECCCLLTTCCCCCDDAAJHHHHHHHHMMMMMMMMMMUUUU
    \\HHHHHHHHHRRAAAAARRAAAKKKKKKKKKKKKKSSSSKSSGGGGGGGGGGGLLLLJJJDDIDDDHDIIIIIIYYYYYSSSSSSSSSSSSSEEEEEEEEEEECELLLLCCCCCDDABHHHHHHHHIIMMMMMMMMMMMUU
    \\HHHHHHHHHRRAAAAAAAAAAAKKKAKKKKKKKKKSSKKGGGGGGGGGGGGGLLLLLJJDDDDDDDDIIIIHHYYYSSSSSSSSSSSSSSSSSEEEEEEEEEEELLLLCCCCCDDBBBBHHHIIIIMMMMMMMMMMMUUU
    \\HOHOHHHHRRAAAAAAAAAAAAKAAAKKKKKKKKKKKKKKKGGGGGGGGGGGGLLLDJDDDDDDDDDDIHHHHHSSSSZSSSSSSSSSSSSSSEEEEEEEEEELLLLLLCCZCDDBBBBBHHIIIIMMMMMMMMMMMUUU
    \\ROOOOHTHRRRAAAAAAAAAAAAAAKKKKKKKKKKKKKKKKGGGGGGGGGGGGGGDDJDDDDDDDDDHHHHHHHZZZSZZSSSSSSSSSSSSSOEEEEEEEEEELLLLLCBUDDDBIIIBHHHIIIMMMMMMMMMMMMUU
    \\ROORRTTHRRAAAAAAAAAAAAAAAKKKKKKKKKKKKKKKKBGGGGGGGSGGGGGDDJDDDDDDDDDDDDHHZZZZZZZZSSSSSSSSSSSSOOEEEUUUUULLLLLLLLBUUDDDDIIIIHIIIIMMMMMVMMMAAAIU
    \\RRRRRTTRRRAAANNAAAAAAAANNKKKNKKKKKKKKKKKBBGGGGGGGGQGGGGGDEDDDDDDDDDDDDDZZZZZZZZZZZISSSSSSSSSOOOEEUUUUUUULLLLLUUUUUDIIIIIIIIIIIMITMCMMMMAAIIU
    \\RRRRRRTRRROOAAAAAAAAAAAANNNNNNKKKKKKKKKKKBBBGBGGGGQGGGGDDDDDDDDDDDDDDDDZZZZZZZZZZZISSSSSSSSSOOOTTUUUUUUUULLLLUUUUIIIIIIIIIIIIIMIICCCMMMIIIII
    \\RRRRRRRRRRRRREEAAAAAAAAANNNNNNKKMMMMKKKKKKBBBBBBBGGGGGGDDDDDDDDDDDDDDDDDZZZZZZZZPZIISSSSSSOOOOOTTTUUUUUUUULULUUUUUUIIIIIIIIIIIIIIIICMCMIIIII
    \\RRRRRRRRREEEEEEEAAAAAAAAANNNNNNKKMMMKKKKBBBBBBBBGGGGGGGGDGDDDJDDDDDDDDUZZZZZZZZZIIIIIIIIOOOOOOOTTTUUUUUAUUUUUUUUUUNIIIIIIIIIIIIIICCCCCIIIIII
    \\RRRRRRRREEEEEEEEAAPAAAAAAANNNNNMMRRMMKKBBBBBBBBBGGGGGGGGGGDDJJJJDDDDDDDQZZZOOZZOOIIIIIIIOOOOOOOOTTUUUMUAAAAUUUUUUUUIIIIIIIIIIIIICCCCIIIIIIII
    \\RRRRRRRRREEEEEEEEAAAAAAKANNNNNLMMMMMMKKBBBBBBBBBGGGGGYGGGGGGGJJJJJJJDDDEZZOOOOOOIIIIIIIJOOOOOOOTTTBHBBBBBBAAIIUUDDIIIIIIIIIIIIIICCCCCIIIAAII
    \\RRRRRRREEEEEEEEEEEEAAAAANNNNNNNMMMMMMBBBBBBBBBBBBBGGGYYYGGGJGJJJJJJJDJDEZZOOOOIIIIIIIIIJJOOOOOOOTBBHBBBBBBYYIIIBBDDDDIIIIIIIIIIIICCCCIIIIAIA
    \\RRRRRRREEEEEEEEEEEEEAEAAENNNNNNNMMMMMMBMBBBBBBGBGGGGYYYYGGGJJJJJJJJJJJJEEEEOOOIIIIIIIIIJJJOOJKOPBBBBBBBBBYYYIIIDDDDDDIDDIIIIIIIIDWWWWWAAAAAA
    \\RRRRRRREEEEEEEEEEEEEEEAEEEEENNNNMMMMMMMMBBBBBBGGGYYYYYYYYGGGJJJJJJJJJJUEEEEOOIIIIIIIIIIJJJJJJKKBBBBBBBBBBVVVVIIIDDDDDDDDDIIIIIWWWWWWWWAAAAAA
    \\RRRRRRRIIEEIEEEECEEECEEEEENNNNNNMMMMMMMMMMBBGGGGGGYYYYYYGGGGJJJJJJJJJJJEEEEOOIIIIIIIIIIIJJKKKKKKKGBBBBBIPIVVVIIIIDDDDDDDDDDIIWWWWWWWWAAAAAAJ
    \\RRRRRRRIIEIIEEEECCECCCEEEEEENNMMMMMMMMMMMMGBBGGGGGYYYYYYYGJJJJJJJJJJJJEEEEEIIIIIIIIIIIIIJKKPKKKKKKBBBBBIIIIIIIIIIIDDDDDDDDDIWWOWWWWWWAAAAAAA
    \\RRRRRRRIIIIIEEECCCCCCCEEEEEMMMMMMMMMMMMMRRGGGGGGGGYYYYYYYYYJJJJJJJJJJJEEEEEEIIIIIIIIIIIIKKKKKKKKKKKKBBBIIIIIIIIIDDDDDDDDDDDDOOOOWWWWWWAAAAAA
    \\RRRRREEEEIIIEEECCCCCCCCEEEMMMMMMMMMMHMMMRRRGGGGGGGYYYYYYYYYUYYJJJJJJEEEEEEEEEEEIIIJIIIIKKKKKKKKKKKKKFBFIIIIIIIIIDDDDDDDOODOOOOOOWWWWWWAAAAAA
    \\IIIIIEEEEEEEEEECCCCCCCCCCEEMMMMMMMHHHHHRRRRGGGGGGGYYYYYYYYYYYYYIJJJJEEEEEEEEEEEIIJJIIIKKKKKKKKKKKKKKFFFIIIIIIIIIDIIDDDDOOOOOOOOIOWWWWAAAAAAA
    \\IIIIIEEEEEEEEECCCCCCCCCCCERMMMMMMMMHHRRRRRGGGGSGGGYYYYYYYYYYYYIIJJJEEEEEEEEEEEEEJJJIOOHHKKKKKKKKKKKKKPFFIIIIIIIIIIIDDDOOOOOOOOOOOWWWWAAAAAAA
    \\IIIIIEEEEEEEEECCCCCCCCCCCCCMMMMMMMHHHRRRRRGGIISSSGYYYYYYYYYYYJJJJJJEEEEEEEEEEEEEJJBBOOHKKKKKKKKKKKKKPPFFIIIIIIIISIIIDDIIOOOOOOOOOOWWWWWAAAAA
    \\IIIIIEEEEEEEEECCCCCCCCCCCCCMMMMMMHHHHRRRRRGHIISSSSYYYYYYYYYYYJVJPJJJEEEEEEEEEELBBBBOOOHKHHKKKKKKKKKKKPBFFIIIIIIISIIIIIIOOHOOOOOOOOWWWWWAAAAA
    \\IIIIIEEEEEEEEQQCCCCCCCCCCCMMMMMMMHHHHHHRRHHHIIIISSYYYYYSSYYYYMPPPPPPPEEEEEEEEEBBBBBOHHHHHHHKKKKKKKKKOPPPPDDSIISSSIIIIIIHHHOOOOOOOOOWWWWWWAAW
    \\NIIIIEEEEEEEEEQQCCCCCCCCCMMMMMMMMHHHHHHHHHHHHIIISSYSSYYSSSYYYMPPPPPPPPEEEEEEEEBBBBBOHHHHHHHHKKKKEEEKKPPDDDDSISEESSSIIIIHHHHHOOOOOOOWWWWWWWWW
    \\IIIDSSQIQQQQEEEQCCCCCCCSSSMMMMMHHHHHHHHHHHHHHIIISSSSSYSSSSSSYYPPPPPPPPEEEEEEBBBBBBBHHHHHHHHHHKKKEEEKKCPPDPDSSSSSSSSIIIHHHHHHHOOOOQOWWWWWWWWW
    \\DDDDDSQQQQQQQEQQCQQCCCXSSSMMMSHHHHHHHHHHHHHHHIIISSSSSSSSSSSSSPPPPPPPPPPEEEEEEBBBBBBHHHHHHHHHHKKKKEPPGPPPPPSSSSSSSSSIHHHHHHHHOOOOOOOWWWWWWWWN
    \\DDDDDSSQQQQQQQQQQQFFFSSSSFMMSSSSSHHHHHHHHHHHBSSSSSSSSSSSSSSSSYYPTPLPPPPEEEEBEBBOBBBHHHHHHHHHHHHPPPPPPPPPPPSSSSSSSSSSCCHHHHHHOOOOOOOWWWWWWNNN
    \\DDDDDSSSQQQQQQQQQQFFFFSSSSSSSSSSSSHHHHHHHHHHHSSSSSSSSSSSSSSSSSDDDPPPPPPEEEEEUUBBBBBHHHHHHHHRHHHHPPPPPPPPPPSSSSSSSSSSHHHHHHHHHOOOONOWWWWWWWNN
    \\SSDDDSSSQQQQQQFFQFFFFFSSSSSSSSSSSHHHHHHHHHHMMSSSSSSSSSSSSSSSSPDDDZPPPPPEEEEZUZRRBBHHHHHHHHHRRHHPPPPPPPPPPPRSSSSSSSSSHHJHHHHGGGGGGWWWWWWWWNNN
    \\SSSSDSSSSSSQQQFFFFFFFFFSSSSSSSSSSSHHHHHHHBHMMMMASSSSSSSSSSSSSDDDDDZPPPZEEEEZZZZREEEEHHHHHRRRRHHHMPPPPPPPPPRPPSSSSSSDDDHHHHHGGGGGGGWWWNNNWNNX
    \\SSSSSSSSSSSQQQSSFFFFFFFFKFFSSSSSSSSHHHHHBBBBMMMMNSSSSSSSSSSSDDZZDZZPZZZEEEZZZZRRREEEHEHHRRRRRRRRRRPPPPPPPPRPPSSSSSSDDDDHDHGGGGGGGWWWNNNNONNX
    \\SSSSSSSSSSSSSSSCFFFFFFFFFFFSSSSSSYYYYHHHHZBBBKKKSSSSSSSSSRSSZZZZZZZZZZZZZZZZZZRREEEEEEHNNRRRRRRRRPPPPPPPPPPPPPPPZSSDDDDDDDDGDLZGGGWNNNNNNNNN
    \\SSSSSSSSSSSSSSSCFFFFFFFFFFFFFSSSSYYYYHHHKBBBBKKKCSCSSSSSSRZZZZZZZZZZZZZZZZZZZZZEEEEEEEENNRKRRRRRRRRPPPPPPPPPPDPDSSDDDDDDDDDDDZZGGGGGNNNNNNNN
    \\XSSSSSSSSSQQQSSSSFFFFFFFFFFFFSSSSYYYYYYKKKEEEERCCCCSSSSSSRZZZZZZZZZZZZZZZZZSUZZZZEEEEEENEERRRRRRRRPPPPPPPPPPPDDDDDDDDDDDDDDDDZZGZZGGGNNNNNNN
    \\SSSSSSXSQQQQQSQFFFFFFFFFFFFSSSSSTTTTYYYYEEEEEERCCCCCSSSSSSZZZZZZZZZZZZZZZZZSUUUSZEEEEEEEERRRRRRRRPPPPPPPPPPPDDDDDDDDDDDDDDDDZZZZZZZGGNNNNNNN
    \\XSSXXXXQQQQQKSQQQFFFFFFFFFWCOSSTTTTTYYYYYYYYEEECCCCCOSSSSZZNZZZZZZZZZZZZSSSSSSSSEEEEEEEEERRRMMRRRPPRPPPPPPFDDDDDDDDDDDDDDDDDVZZZZZZGGGNNNNNN
    \\XXXXXXXXQQQQQQQQQFFFFFFFFFWCCCCCTTTTYYYYYYYYCRRCCCCKOSOOSNNNZZZZZZZZZZZZZSSSSSSSSEMMMEEEEMMMMMRRRRRRRPPPFPFDDDDDDDDDDDDDDDGGZZZZZZGGGGGGGNGG
    \\XXXXXXXQQQQQQQQQQQFFZZZZZZZZZZHHTTTTTTYYYYYYCCCCCCOOOOOOOINNZZZZZZZZZZZZZSSSSSZZZZMMMMEEEMMMMMRRRRRRRPRRFFFFJJJJJDDDDDDDDGGZZZZZGGGGGGGGGGGG
    \\XXXXXQQQQQQQQQQQQQFFZZZZZZZZZZZZZZZZTTYYYYYYCCCCCOOOOOOOOINZZZRRRRZRRZZZSSSSSSSZZZZMMMMMMMMMMMMRRRRRRRRRRRLLMJJJJJDDDDDDDDGGGZGGGGGGGGGGGGGG
    \\XXXXXQQRQQQQQQQQQQFFZZZZZZZZZZZZZZZZYYYYYYYYCCCCCCOOOOOOOOXZRRRJRRRRRZZSSSSSSSSZZZZMMMMMMMMMMMMRRRRRRRRRRRLLJJJJJJJDJJDDDDGGGGGGGGGGGGGGGGGG
    \\XXXXXXXQQQQQQQQQQQFFZZZZZZZZZZZZZZZZYYYYYYYYCCCLLOOOOOOOOOXXRRRRRRRRSZSSSSSSSSSYZZZZMMMMMMMMMMMMRRRRRRRRLLLLJJJJJJJJJJDDDGGGGGGGGGGGGGGGGGGG
    \\XXXXXXQQQQQQQQQQQQQFZZZZZZZZZZZZZZZZYYYYYYYYCLCLLOOOOOOOOOOORRRRRRRRSZSSSSSSSSSYYYZZMMMMMMMMMMMMMRRRRRWRLLLDJJJJJJJJJJJJGGGGGGGGQGGGGGGGGGGG
    \\XXXXXXQQQQQQQQQQQQQFZZZZZZZZZZZZZZZZYYYYYYYYCLLLLLLLOOOOOOOORRRRRRRRSZSSSSSSSYYQYYYZMMMMMMMMMMMMMRRRRRRLLLLJJJJJJJJJJJJJGGGGGGGGQQGGGGGGGGGG
    \\XXXXXXQQQQQQQQQQQQQFFFQQQQQQQZZZZZZZTYYYYYYYLLLLLLAAOOOOOKOOORRRRRRRSSSSSSSYYYYYYYYYYLLLMMMMMMMMRRRRRRRLLLLLJJJJJJJJJJGGGGGGGGGGQAGGGGGGGGGG
    \\XXXXXXQQQQQQQQQQQQQFFFQQEQQQQZZZZZZZTTTTTNTPLLLLALAOOOOOOOOOORRRRRIPSSYRSIYYYYYYYYYYYLYMMMMMMRMPRGGRRRLLLLLLJJJJJJJJJJGGGGGGGGGQQQGGGGGGGGGG
    \\XXXXXXQQQQQQQQQQQQQQEEEEEQZZQZZZZZZZZTTTTTTTAALAAAAOOOOOOOOOOXXRRIIPSSYYSYYYYYYYYYYLYYYYYPMMMMMPRGRRRRRRLLLLLJJJJJJJJJGGGQQGQQGGQQGGGGGGGGGG
    \\XXXXXXXQQQQQQQQQQQQQQQQEEQZZZZZZZZZZTTTTTTTTTAAAAAAOOOOOOOOXXXXXIIIIYYYYCYYYYYYYYYYYYYYYPPPPMPPPPPRRRGRLLLLLLLVJJVJJJGGGGQQGQQQQQQAQGGGGGGGG
    \\XXXCXXXXXQQQQQQQQQQQQQRREZZZZZZZZZZZTTTTTTTTTTAAAAAAAOOOOXXXXXXXIIIIYYYYYYYYYYYYYYYYYYYPPPPPMMPPPRRRGGGLLLVVLVVJJVJJJGQQQQQQQQQQQQQQQGGGGGGG
    \\CCCCCCXXXQQQQYQQQQQQQBROOOOOOZZZZZZTTTTTTTTTTTTTAKAAOOOOOXXXXXXXIIIYYYYYTTYYYYYYYYYYYYYYPPPPMPPPPRRRPGGGVVVVVVVVVVVVQQQQQQQQQQQQQQQQQGGGGGGG
    \\CCCCCCCXXYQQYYBBQQQQBBROOOOOOZZZZZTTTTTTTTTTTTEKKKKKKOXXXXXXXXXXIIIYYYTYTTYYYYYYYYYYYYPPPPPPMPPPPPPPPPGGVVVVVVVVVVVVNNQQMQQQQQQQQQQQQGGGGGGG
    \\CCCCCCCXYYYYYYBBQQBBBBOOOOOOOZZZZTTTTTTTTTTTTKKKKKKKKKXXXXXXXXXXIIITTTTTTTYYYYYYYAYYYAPPPPPPPPPPPPPPPGGGVVVVVVVVVVNNNQQQMQQQQQQQQAQQGGGGCGGG
    \\CCCCCYYYYYYYYYBBBBBBBBOOOOOOOZZZZTTTDFTTTTTTTTKKKKKKKKKXXXXXXXXXIITTTTFTTTTYYYYYYAAAYAAAAPPPPPPPPPPPPGGGGVVVVVVVVVNNNMMMMMMQMQQQQQVVVVVGCGGG
    \\CCCCCXYYYYYYYYBBBBBBBBOOOOOOOZZZZZZTDDDTTTTTKKKKKKKKKKKXXXXXXXXXXXXTTTFFFYYYCYYYAAAAAAAAAPPPPPPPTTTTRRRGGVVVVVVVVVVVNNNMMMMMMMRRRRRVNVVGCCCC
    \\CCCCCCUYYYYYYYYBBBBBBBOOOOOOOOOOZZZDDDDDTTTTKKKKKKKKKKKXXXXXXXXXXXXTTTFFFFFFFTYYAAAAAAAAAAPPPPPTTTXRRRRBBBVVVVVVVVVNNNMMMMMMMMMRRRRVVVVCCCCC
    \\CCCCCCCYYYYYYYYYYZBBBBBBOOOOOOOOOZZZDDITTTTTKKKKKKKKKKXXXXXKKXXXXXXTFFFFFFFFFYYAAAAAAAAAASPPPPPTTTTTTAABBPVVVVVVVOVVMNVMMMMMMRMRRVVVVVVCCCCC
    \\CCCCCCCCYYYYYYYTTTTBSBOOOOOOOOFOZZZDDDDTTTTKKKKKKKKKKKKKXXXKKKKXXXXTFFBFFFFFFFFAAAAAAAAAAAPPPTTTTTTTTBBBBBBVVVVVVVVPMMMMMMMMRRRRRVVCVVVVVCCC
    \\CCCZZCCYYYYYYYTTTTTTTFOOOOOOOOOZZZZDDDDTTTHHHKKKKKKKKKKKXXXXXKXXXXTTFBBFFFFFFAAAAAAAAAAAAAAAJJJJTJJJBBBBBPVVVVVPPVPPMMMMMMMMRRRRRYYCCVVVVCCC
    \\CCCZZZZZZZYYYTTTTTTTTOOOOOOOOOOOOZZZZZZZZHHHHKKKKKKKKKKKXXXKKKXXKKTTTTQQQQFFCAAAAAAAAAAAAAAJJJJJTJJJBBBBBPPPPPPPPPPPMMMMMMMMMRMMMYYCCCCCCCCC
    \\CCCCZZZZZYYZYTTTTTTTTOOPOOOLOOOZZZZZHHHHHHHHKKKKKKKKKKKKXXKKKKOOKETTTGQQQQCCCCVAAAZAAAAAAAAAAAJJJJJBBBBBPPPPPPPPPPPPMMMMMMMMMMMMMYYYYYYCCCCC
    \\CZCZZZZZZYYZZZZTTTTTTTOODOOTTDZZZZZZDHHHHHHHHKKHHKKKKKXXXKKKKKKKKKKKSKKQQQCCCCCCAFAAAAAQAQQQAJJJJJJJBPBPPPPPPPPPPPPPPPMMMMMMMMMBBRYYYYCCCCCC
    \\ZZZZZZZZZZZZZZTTTTTTTTOOOOOTTDDDDDDZDDHHHHHHHHHHHKKKKKKKKKKKKKKKKKKKKYKQCCCCCCCCCCCVAAOQVQQQQJJJPPPPPPPPPPPPPPPPPPPPPPMMMMMMMBBBBYYYCCCCCCCC
    \\ZZZZZZZZZZZZZZZTTTTTTTTOTTTTTDDDDDDDDDDDHHHHHHHHHKKKKKBKKKKKKKKKKKKKKKKCCCCCCCCCCCVVAQQQQQQQQJJJPJJJPPPPPPPPPPPPPPPPPPMMMMMBBBBBBBBBCCCCCCCC
    \\ZZZZZZZZZZZZZZZTTTTTTTTTTTTDDDDDDDDDDDDDHHHHHHHHHHKKKBBBBKKKKKKKKKKKKKKCFCCCCCCCCCCVAUQQQQQJJJJJJJJJPPPPPPPPPPPPPPPPPPPPMMBBBBBBBBCCCCCCCCCC
;
