const std = @import("std");

pub fn main() void {
    part1();
}

fn part1() void {
    var total_price: usize = 0;
    var visited: Visited = [_][COLUMNS]bool{
        [_]bool{false} ** COLUMNS,
    } ** ROWS;
    for (0..ROWS) |y| {
        for (0..COLUMNS) |x| {
            if (visited[y][x]) continue;
            total_price += RegionExplorer.explore(
                .{ .x = x, .y = y },
                &visited,
            );
        }
    }

    std.debug.print("Total price: {}\n", .{total_price});
}

const Visited = [ROWS][COLUMNS]bool;

const RegionExplorer = struct {
    visited: *Visited,
    plot_type: u8,
    area: usize,
    perimeter: usize,

    fn explore(starting_plot: Plot, visited: *Visited) usize {
        const plot_type = starting_plot.getChar();
        var self = RegionExplorer{
            .visited = visited,
            .plot_type = plot_type,
            .area = 0,
            .perimeter = 0,
        };
        self.visitPlot(starting_plot);
        return self.area * self.perimeter;
    }

    fn visitPlot(self: *RegionExplorer, plot: Plot) void {
        if (self.visited[plot.y][plot.x]) {
            return;
        }

        self.area += 1;
        self.visited[plot.y][plot.x] = true;

        var neighbour_count: usize = 0;
        const directions = [_]Direction{ .Left, .Up, .Right, .Down };
        for (directions) |direction| {
            const neighbour = plot.getAdjacant(direction) orelse continue;
            if (neighbour.getChar() != self.plot_type) {
                continue;
            }
            neighbour_count += 1;
            self.visitPlot(neighbour);
        }

        self.perimeter += 4 - neighbour_count;
    }
};

const Direction = enum { Left, Up, Right, Down };

const Plot = struct {
    x: usize,
    y: usize,

    fn toInputIdx(self: *const Plot) usize {
        return self.y * (COLUMNS + 1) + self.x;
    }

    fn getChar(self: *const Plot) u8 {
        return input[self.toInputIdx()];
    }

    fn getAdjacant(self: *const Plot, direction: Direction) ?Plot {
        switch (direction) {
            .Left => {
                if (self.x == 0) return null;
                return Plot{ .x = self.x - 1, .y = self.y };
            },
            .Up => {
                if (self.y == 0) return null;
                return Plot{ .x = self.x, .y = self.y - 1 };
            },
            .Right => {
                if (self.x + 1 == COLUMNS) return null;
                return Plot{ .x = self.x + 1, .y = self.y };
            },
            .Down => {
                if (self.y + 1 == ROWS) return null;
                return Plot{ .x = self.x, .y = self.y + 1 };
            },
        }
    }
};

const ROWS = blk: {
    @setEvalBranchQuota(30000);
    var rows: usize = 0;
    var row_iterator = std.mem.split(u8, input, "\n");
    while (row_iterator.next()) |_| {
        rows += 1;
    }
    break :blk rows;
};

const COLUMNS = blk: {
    var row_iterator = std.mem.split(u8, input, "\n");
    const row = row_iterator.next().?;
    break :blk row.len;
};

// const input =
//     \\RRRRIICCFF
//     \\RRRRIICCCF
//     \\VVRRRCCFFF
//     \\VVRCCCJFFF
//     \\VVVVCJJCFE
//     \\VVIVCCJJEE
//     \\VVIIICJJEE
//     \\MIIIIIJJEE
//     \\MIIISIJEEE
//     \\MMMISSJEEE
// ;

const input =
    \\RRRRJJKKKKKKKKKKKKKKKKKKKKKNEEEEEEEEEEEMMMMMMMMMMMMMMZZZZZZZZZZZUUUUUURXXXXXXXXXXXXDDDDDDQQQQQQQOPPPOOOOOXXXXXXXHHYHBBBSKKKKKLLLBBBBBBBBBJBC
    \\RRRRJKKKKKKKKKKKKKKKKKKKKKKNNEEEEEEEEEEMMMMMMMMMMMMMMZZZZZZZZZZZUUUUUUXXXXXXXXXXXXDDDDKKKKKKKPXVOOOOOOOOOXXXXXXXHHHHHSSKKKKKKBBBBBBBBBBBBBBC
    \\RRRRJJJKJKKKKKKKKKKKKKKKKKKNNEEEEEEEEEEEEMMMMMMMMMMZMZZZZZZZZZZUUUUUUUMMXXXXXXXXXXDDDKIKKKKKKKXXXXXOOOOXXXXXXXXXHHHHHHSKKKKKKPPHBBBBBBBBBBBC
    \\RRRRRRJKJKKKKKKKKVKKKKKKKKNNNEEEEEEEEEEEMMMMMMMMMMMZZZZZZZZZZZZUUUUUUUMMMXXXXXXXXXXXXKKKKKKKKXXXXXXSOOOOXXXXXXXXHHHHHHHKKKKKKPPPPBCBBBBBBBBZ
    \\RRRRRJJJJJJKKKKKKVKKKKKKKNNNNEEEEEEEEEEEDMMMMMMMMMMZZZZSSSZZZZZZUUUUUUUUXXXXXXXXXXXKKKKKKKKKKXXXXXXOOOOXXXXXXXHHHHHHHHSKKKKKKPCCCCCCBBBBEZZZ
    \\NNRRRJJJJKKKKKKVVVKKKKKKKNBNNNEEEEEEEEEDDMMMMMMMMMMMMMSSSZZZZZZZZUUUUUUKXXQXXXXXXXXKKKKKKKKKKXXXXXXXXOOXXXXXXXXHHHHHDSSKKKKKKPCACCCCBBZZZZZZ
    \\NRRRRHJJKKKKKVVVVVVKVKKKKNNNNEEEEEKKEEEDDDMMMMMMMSSSSMMSSZZZZZZZUUUUUUUUXXXXXXXXXXKKKKKKKKKKXXXXXXXXXXXXXXXXXXXHHHHHSSSKKKKKKPPPCCCCABZZZZZZ
    \\NNNNHHJKKKKKKKVVVVVVVVWWKNNMMMEEEKKEEBDDDDDMMMMMMSSSSSSSSSZZZZUUUUUUUUUUXXXXXXXXMMMMKKKKKKKKXXXXXXXXXXXXXXXXXXXHHHHHSSSSSSKKKPPOCCCCABZZZZZZ
    \\NNNNHHHHHHHHVVVVVVVVVWWWWWNMMMEEKKKKKDDDDDDMMMMSSSSSSSSSSQQZZUQQQUUUUUUUXOOXXXXMMMMMMMKKKKKKXXXXXXXXXXXXXXXXXXHHHHHHSSSSSSKKKPPOOOCCABZZZZZZ
    \\NNNNHHHHHHHHHVVVVVVVMWWWWWWWWMEEEEKKKDDDDDDDDMMMMSSSSSSSSQQZZUQUUUUUUUUUUUOMMXMMMMMMMMKKKKKXXXXXXXXXXXXXXXXXXXXXXHHSKKKKKKKKKKPPPOCHZZZZZZZZ
    \\NNNNNHHHHHHHHVVVVVVVVWWWWWWWWMEENNNKDDDDDDDSDDMMMLSSSSSSQQZZZUUUUUUUUUUUUUOMMMMMMMMMMMMKKKKXQQQXXXXXXAXXXXXXXXXXXXHSKKKKKKKKKKPPPOZZZZZZZZZZ
    \\NPNPHHHHHVVVVVVVVVVWWWWWWWWWWMEEENNNDDDDDDDDMMMMLLSSSSSSSQQQZQQUMUUUUUUUUUOMMMMMMMMMKKKKKKKKXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKPPPOOZZZZZZZZZ
    \\PPNPUUHHHVVVVVVVVVVVWWWWWWWWWWDDEDDDDDDDDDDDDDLLLLLSSSQQQQQQQQQUUUUUUUUUUUMMMMMMMMMMBBBBBRKKEEEEXXEXXXXXXXBXXBXXXXXXKKKKKKKKKKPPOOOZOOZRRRZZ
    \\PPPPPUUUUUVVVVVVVVVVWWWWWWWWWWXXAAUDDDDDDDDDDDLLLLLSQQQQQQQQQQUUUUUUUUUUUMMMMMMMMMMMBBBBBRKKEEEEXXEXXXXXXBBXXBXXXFXMKKKKKKKKKKPPOOOZOORRRRZZ
    \\PPPPUUUUUUUVVVVVVVVWWWWWWWWWWCXXAAUDDDDDDDDDDDLLLLLSQQQQQQQQQQUQUUUUNUUUMMMMMMGMMMMBBBBBBBBEEMMMMXXXXXXXXBBBBBFFEFFFMKKKPPPPPPOOOOOOOOORRRZZ
    \\PPPPUUUUUUUVVVVVVVVVWWWWQQQQQQQQUUUUDDDDDDDDDDDLLLSSQQQQQDDQQQQQUUNNNNNNNNNMMQBBBMBBBBBBBBBBEBBMMMMMMMMXXBBBBBFFFKKKKKKKVPPPPPOOOOOOOORRRRZS
    \\PPPPPUUUUUUUVVVVVVVWWWWWQQQQQQQQUUUUDDDDDDDDLDDLLLLLQQDQQDDDDDQQUUNNNNNNNNNMMQQBBBBBBBBBBBBEEBMMMMMMMMMXXBBBBBFFFKKKKKKKVVPPPPPOOOOOORRRRRSS
    \\PPPPPPUUUUUUVVVVTTTTNWWWQQQQQQQQUUUUDDDDDDDLLLDLLLLQQDDDQQDDDDDUUNNNNNNNNNNNNNNNBBBBBBBBBBBBBBMMMMMMMMMEBBBBBBFFKKKKEEEEVVVFPPOOOOOOORRRRRRS
    \\PPPPPPUUUUUUVVTTTTTTTWWWQQQQQQQQUUUDDDDDDDDLLLLLLLLQDDDDDDDDDDDDUUNNNNNNNNNNNNNNSBBBBBBBBBBBBBBMMMMMMMMEIBBBBFFFKKKFEEEEFFFFFFOOOOORRRRRRSSS
    \\PPPPPUUUTUTUTTTTTQQQQQQQQQQQQQQQUUUUSSSDDDSLSLLLLLLLLDDDDDDDDVDDAANNNNNNNNNNRRNNSBBBBBBBBBBBBBBMMMMMMMMIIIBTIFFFKKKFEEEEFFFFFFOOORRRRRRGGSSS
    \\PPPPPPTTTUTTTTTTTQQQQQQQQQQQQQQQUUFSSSSSSSSLSSLLLLLLLDDDDDDDDDDDJJNNQNNNNNNSSSSSSBBBBBBBBBBBBBMMMMMMMMMMIIIIIFQFFEEEEEEEEEEFVFFRRRRRRRRGGSSS
    \\PPPPPPYYTTTTTTTTTQQQQQQQQQQQQQQQUUFFSSSSSSLLSSSLLLLLLDDDDDDDDDDDJJJJNNNNNNNRSSSSYYBBBBBBBBFFBBMMMMMMMMMMIIIIIFFFFEEEEEEEEEEVVVVRRRRRRRRRGSSS
    \\PPPPPPJTTTTTTTTTTQQQQQQQQQQFFFFFFFFAAISSSSSSSSLLLLLLZDDDDDDDDDJYJJJJJJJNNSSSSSSSYBBBBBBBBBFFMBMMMMMMMMMMIIIIIFFFFEEEEEEEEEEVVVRRVRRRRRRRRSSS
    \\PPPJJJJJJJJTTTTTTQQQQQQQQQQFFFFFFFAAIIISSSSSSLLLLLLZZDDDDDDDDJJJJJJJJJJNSSSSSSSSSBBBBBBCCAMMMMMMMMMMMMMMMMIIIIFIIEEEEEEEEEEEEEERVRRRRRRFRSSS
    \\PPPJJJJJJJTTTTTTTQQQQQQQQQQFFFFFAAAAAAASSSSSSLLLLLZZZZZDDDDDJJJJJJJJJJJJJSSSSSSSSSVBBBBCCMMCCUMMMMXXMMMMMMIIIIIIIEEEEEEEEEEEEEEVVVRRRRRRRUSS
    \\PPPJJJJJJJDTTTTTTQQQQQQQQQQFFFFAAAAAAAASSSSZZLLZLZZZEZDDDDSSSSJJJJJJJJJJJSSSSSSSSSVVBBCCCCCCCUMMMMXXXXXDDDIIIIIIGEEEEEEEEEEEEEEVVRRRRRRRRUUS
    \\PPMJJVJJJJJTTTTTTQQQQQQQQQQOOFFFAAAAAAAASZZZZZZZZZZEEEEDDDSSSSHHHJJJJJJJJSSSSSSSSSBBBBCCCCCCCCCXCCXXXDDHDIIIIIIIGEEEEEEEEEEEEEEUURURRRRRRUSS
    \\PMMMFMBBJJTTTTNNNNNNQQQQQQQOOFFAAAAAAAAAAZZZZZZZZZZZEEEEESSSHHHHHHJJJJJJSSSSSSSSSSSSBCCCCCCCCCCCCHXXXDHHHIIIIIIGGEEEEEEEEEEVVVUUUUUUURRRUUSS
    \\PMMMMMBBBTTTTTNNNNNNQQQQQQQOOAAAAAAAAAAAZZZDZZZZZEEEEEEEEHHHHHHHHHHJJJJSSSSSSSSSSSSSSCCCCCCCCCCCQXXYYHHHHHIIGGIGGEEEEEEEEEECCCCUCUUUURRUUUUU
    \\MMMMMMMBTTTTBBNNNNNNTOOOOOOOAAAAABAAAAAAZWZDDDDZZEEEEEEEEHHHHHHHHHHJJJJSSSSSSSSSSSSSSCCCCCCCCCCQQQHHHHHHHHIIGGGGGGGGGGGGCCCCCCCWCCCUURUUUUUU
    \\MMMMMMMMTTNNNNNNNNNNTOOOOOOOOAAAABABAAAAZWWDDDDDDEEEEEEEEHHHHHHHHHHOJJSSSSSSSSSSSSSSSCCCCCCCCCCQQQHHHHHHHHIIGGGGGGGGGGGCCCCCCCCCCCCUUUUUUUUU
    \\MMMMMMMMMTNNNNNNNNNNOOOOOOOOOARABBBBAXAPWWWDDDDDDOEEEEEEEHHHHHHHHHHHHHSSSSSSSSSSSSSSSSCCCCCCCCCJHHHHHHHHHHCIIGGGGGGGGGGCCCCCCCCCCCCUUUUUUUUU
    \\MMMMMMMMMMNNNNNNNNNNOOOOOOOOOOBZBBBBIBPPWWWWDDDDDOEEEEEEEEYHHRRRRRRHHHHSSSXXSSSSTTTSSSCCCCCCCCJJHHHHHHHHHCCIKGGGGGGGGGGGGCCCCCCCCCCCUUUUUUUU
    \\MMMMMMMMMMBBBBNNNNNNOOOOOOOOBBBBBBBBBBBBWWWWWDDDOOEEEEEEEHHHHRRRRRRHHHSSSSXXXHHTTTTTTSCTGCCCCJJJJHHHHHHHHCIIKKGGGGGGGGGCCCXXXXXXXCCUUUUUUUUU
    \\MMMMMMMMMXBBBBNNNNNNOOOOOOOBBBBBBBBBBLLLLWWWWDDDDOOOEEEEKKHHHRRRRRRHHHBBSXXXXHHTTTTTTSTTGGCTCJJJHHHHHHHHHHXMKKGGGGGGGGCCCCXXXXXXXXXXXXXXUUUU
    \\MMMMMMMMMXBBBBNNNNNNXOOOOOOBBBBBBBBBBBBLWWWWWDOOOOOOEEEEEKKRRRRRRRRHBBBBBBHXHHHHHHTTTTTGGCCCGJJHHHHHHHHHHHXMMMGGGGGGGCCCCCXXXXXXXXXXXXXXUUUU
    \\MMMMMMMMMMMBBBNNNNNNOOOOOBBBBBBBBBBBBLLLWWWWWBBOOOOOOOEEKKKRRRRRRRRHBBBBBHHHQHHHHHHTTTTGGGGGGGHHHHHHHHHHHHHMMMGGGGGGGCBCCCXXXXXXXXXXXXXXUUUQ
    \\MMMMMMMMMBBBBBBBBIIIIOOOOBBBBBBBBBBBBLLIWWWWBBBOOOOJJOEEEEERRRRRRRRRBHHHHHHHHHHHHHHTTTTGGGGGGHHHHHHHHHHHEEMMMMGGGGHGGTBBCCXXXXXXXXXXXXXXUUUQ
    \\MMMMMMMMMBBBBBBBIIIIDOODDMDBBBBBBBBBBWWWWWWBBBBBBBOJJJJIEEKRRRRRRRRRHHHHHHHHHHHHHTTTTTTGGGGGGGHHHTTTHHHHEEMMMGGGGGGGTTTBBCXXXXXXXXXXXXXXUUUQ
    \\MMMMMMMMMMMFBBBBBBBBDDKDDDDDBBBBBBBBBNBBBBBBBBBBBBJJJJJJJJKKKRRRRRRRRHHHHHHHHHHHHHHHTMMMGGGGGGHHTTOOHHHHHEMEEEGTTGGTIITTTCXXXXXXXXXXXXXXUUUQ
    \\MMMMMMGMGGGGQQBBBKEDDDDDDDDDDDNBBBBNBNNNNBBBBBBBQQJJJJJJJJKKRRRRRRRRRHHHHHHHHHHHHHMMMMMMMGGGGGGHTTOOHOOOEEEEEEETTGSTITTTTCXXXXXXXXXXXXXXUUUQ
    \\MMMMMMGGGGGGQQQQKKEDDDDDDDDDDDNBBBBNNNNNNBBBBBBBQQJJJJJJJKKRRRRRRRRRRHHHHHHHHHHHHHJHMMMMGGGGGGGOOOOOOOOOEOOEEEETTGGTTTTTTTXXXXXXXXXXXXXXUUUQ
    \\MMMMMMMKGKKGKKQKKKDDDDDDDDDDNNNNBBNNNNNNBBBBBBBBBBJJJJJJJKKRRRRRRRRRRNHHHUUHHHHHHHHHMMOOOOGGGGGOOOOOOOOOOBOOEOOTTGGTTTTTTTXXXXXXXBUUUMUUUUUQ
    \\DMMMMMMKKKKKKKKKKPDDDDDDDDDDDNNNNNNNNNNNNBBBBBBBBBBJJJJJJKKKRRRRRRRRRRNHHHHHFHHHHHHHHMMOOOGOOGGFOOOOOOOOOOOOOOOTTGGGTTTTTTTTHHZZUUTUUUUUUUUQ
    \\DMMMMMMKKKKKKKKKKPPDDDDDDDDDDDNNNNNNNNNNNBBBBBBBMBJJJJJJKKKRRRRRRRRRRPHHPPPHHDHHHHMMMMOOOOOOOOFFFOOOOOOOOOOOOOOOTTTTTTTTTTTTHHZHUUUUUUUUUUUU
    \\DDMMDDDKKKKKKKKKKKPPDDDDDDDPDNNNNNNNNNNNNNBBBBBMMJJJJJJJJJWRRRRRRRRRRPPPPPPPPHHHHHMMMOOOOOOOOOOOOOOOOOOOOOOOOOOTTTTTTTTTTTTTTHHHUUUUUUUUUUUU
    \\DDDDDDDKKKKKKKKKKKKDDDDDDDDDDNNNNNNNNNNNNNBBXMMMMJJOJJJJJWWRRJRRRRRRRPPPPPPPPPHHMMMMMMOOOOOOOOOOOOOOOOOOOOOOOOOOTTTTTTTTTTTTTHHHUHHUUUUUUUUU
    \\DDDDDDDDKKKKKKKKKKKKDDDDDDDDZZNNNNNNNNNNNNBBMMMMJJJOOJJJJWWWWRRRRRRRRRPPPPPPPPSMMMMMMOOOOOOOOOOOOOOOOOOOOOOOOZZTTTTTTTTTTTTTTHHHHHHUUUUUUUUU
    \\DDDDZZDDDKKKKKKKKKKKPDDDDDDDDZZZNNNGNNNNNNNNNOOOJJJOOLJUJJWWWRRRRRNRPRPPPPPPPPSSSSSSOOOOOOOOOOOOOOOOOOOOOOOOOVZTZZTTTTTTTTTTTTHHJJUUUUUUUUUU
    \\DDZZZZZZDDKKKKKKKKDPPDDDDDDDZZZZZNNNNNNNJNOOOOOOOOOOOOJWWWWWWWRRRRRRPPPPPPPPPSSSSSSKOOOOOOOOOOOOJOOHOOOOOZOOVVZZZZZZTTTTTJTTTTHHJJUUIUUUUUUU
    \\ZZZZZZZZZDKKKKKKKKDDDDDDDDSDZZZZNNNNNNNJJJOOOOOOOOOOOOOOWWWWWWRRWRRRPSPPPPPSSSSSSSSSSOOOOOOOOOOJJOOHOOOOOZZRZZZZZZZSSSSTSJTTZJHHHJJJJJURRUUU
    \\ZZZZZZZZZKKKKKKKKZZZDDDZZDDDDZZZFNNNNNNZJJOOOOOOOOOOOOOOOWWWWWWWWRRWSSSSSPPSSSSSSSSSSOOOOOOOOOOOBHHHOOOOOZZZZZZZZZZSSSSSSJJJJJHHJJJJJJURRRUU
    \\ZZZZZZZZZKKKKKKKKZZZZDZZZZZZZZZZZNNNNNZZJJAOOOOOOOOOOOOWWWWWWWWWWWRWSSGSPPSSSSSSSSSSSSOSOOOOOOOOBHBHOMMMZZZWWZZZZZZSSSSSSSJJJJJJJJJJJJRRRRUU
    \\ZZZZZZZZZKKIKKKKKZZZZZZZZZFFFFZZZZNNNNZZJJAAOOOOOOOOOOOWWWWWWWWWWWWWSSSSSPSSSSSSSSSSSSSSSOOBBBBBBBBHOMMMZZZZZZZZZZSSSSSSSSSJJJJJJJJJJJJRRRRU
    \\ZZZZZZZZRRRRKKKKKQZZZZZZZZFFFFFFDDDDDNZZJJOOOOOOOOOOOOOOWWWWWWWWWWWSSSSFSSSSSSSSSSSSSSSSBBOBBBBBBBBHOOMMOOEZZZZZSSSSSSSSSSJJJJJJJJJJJJRRRRAU
    \\ZZZZZZRZRRRRRRRRRRZZZZZZZFFFFFFFDDDDDDYYJYOOOOOOOOOOOOWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSUBBBBBBBBBBBBBOOOOCOOZZZZZSSSSSSSSSSJJJJJJJJJJJJRRRRAA
    \\ZZZZZZRRRRRRRRRRRRRZZZZZFFFFFFXFFFFFYYYYYYOOOOOOOOOOOGWWWWWWSWWWWWWWSSSSSSSSSSSSSSSSSUUBBBBBBBBBBBPBOOOOOOZZZZZZZZSSSSSSSJJJJJJJJJJJAJAAAAAA
    \\ZZZZZZRRRRRRRRRRRZZZZZZZFFFFFFFFFFFQQQYYYOOOYYYYOOOOOOOWWWSSSSWWWWWWSSSSSSDDSDSSOSSSSUUBBBBBBBBBBBPOOOOOONZZZZZZZZSSSSSSSJIJJJJJJJJJAAAAAAAU
    \\SZZZZZRRRRRRRRRCAZZZZOZFFFFFFFFFFFFQVVYYYYYOYYYYYOYYOOSWWWWSSYSWWWWWSSSISPDDDDSDDDUUUUUBBBBBBBBBBBOOOOOORZTZZZZZZSSSSSSSSJIJJJJJJJJJJAAAAAAA
    \\SSZZZSSRRRRRRRRAAOOOOOOOFFFFFFFFFFFQVVYYYYYYYYYYYYYYYYWWWWSSSSSSWWSWSSPIPPDDDDSDDDDDUUUUUBBBBBBBBBHOOOOORZZZZZZZZIISIISSSUIJJJJJJJJJJAAAAAAA
    \\SSSZSSSRRRRRRRRAAAOOOOFFFFFFFFFFFFQQVQQYYYYYYYYYYYYYYYCWWSSSSSSSWSSSSSPPPDDDDDDDDDDDBUUBBBBBBBBBBBOOOOOOOZZZZZZIZZIIIISIIIIJJJJJJJJJAAAAAAAA
    \\SSSSSSSRRRRRRRRRROOOOFFFFFFFFNFFFFQQQQQYYYYYYYYYYYYYYYCWSSSSSSSSWSSSSSPPPDDDDDDDXXXIBUBBBBBBBBBBBBPPPPTRRTZZZZIIZIIIIIIIIIIIIJJJJJJAAAAAAAAA
    \\SSSSSSSSRRRRRQQQQOOOOAAAAFFFFFFFDDDQQQQYYYYYYYYYYYYYYYYWDSSSSSSSSSSSPPPPPPPDDDDDDXXXBBBBBBBBBBBBBPPPPTTTTTZRZZZIIIIIIIIIIIIIJJJJJJNBBAAAAAAA
    \\SSSSRRRRRRRRRQQQQOOOAAAAAAAFFFFDDDDQQQYYYYYYYYYYYYYYYYUSSSSSSSSSSSSSPPPPPPPDDDDDDXXXBBBXBBBBBBBBBRRRTTTTTTTRZZZIIIIIIIIIIIIIIIJJNJNNAAAAAAAA
    \\SSSSRRRRRRRRRQQQQQQOAQQQQQFFFFDDDDQQYYYYYYYYYYYYYYYYYYUUUUUSSSSSSSPPMPPPPPPPYDDDXXXXXXXXXBCBBBSBSTTRRTTTTTTTTTIIIIIIIIIIIIIJJJJJNNNNNAAAAAAA
    \\TSSSRRRRRRRRRRRQQQQQQQQQQQFFFEEDDEQEYYSSSYYCCCYYYYYYYYUUUUSSSSSSSPPPPPPPPPPYYYYRXXXXXXXXXXXXXSSSSTTRRTTTTTTTTTTTTTNIIIIIIIIJJJJJNNNNNAAIAACC
    \\SSSSRRRRRRRRRRRQQQQQQQQQQQEEEEEDEEEEYESSSYDICCPUUYUYYCUUUUUUUSSSSPPPPPPPPPYYYYYRXXXXXXXXXXXXSSSSSTTTTTTTTTTTTTTTTTTIIINIIIJJJNNNNNNNNNANAACC
    \\HHHHHRHRRHHHHHRQQQQQQQQQAAAEEEEDDEEEEEEESSIIIEUUUUUYYYUUUUUUUUSSSPPPPPPPPPYYYYYRXYXXXXXXXXXXXXXXSTTTTTTTTTTTTTTTTVTIIIIIIIJWWNNNNNNNNNNNAACC
    \\HHHHHHHHHHHHHHHQQQQQQQQQAAAEEEEEEEEEEEESSSIIIIIZZUUUUUUVVVUUUSSJPPPPPPPPPPYYYYYRYYXXXXXXXXXXXSXSSSTTSSTTTTTTTTTTTTAAAIDDDDJWWNNNNNNNNNNNNAAA
    \\HHHHHHHHHHHHRRRRRAQQQQQQAAAAEEEEEEEEEEEEIIIIIIDIZZUUUUUVVVVVVSSJPPPPPPPPPPYYYYYYYYXXXXXXXXXSSSSSSSSSSSTTTTTTTTTTTTAAAAADHHJWWHHHNNNNNNNNNANB
    \\HHHHHHHHHHHRRRRRAAAAAAAAAAAAEEEEEEEEEEEGGIIIIIDIIIUUUUUVVVVVVBJJJJPPPIIBYYYYYYYYYYXXXXXXXXSSSSSSSSCCCSTTTTTTTTTTTTAAAAAAHHHHHHHHNNNNNNNNNLNB
    \\HHHHHHHHHHHHHHRRAAAAAAAAAAAEEEEEEEEEEEGGGIIIIIIIUHUUUUVVVVVVVBIJJJPXPIIYJYYYYYYYYYXXXXXXXXXXSSSSSSCCCCCCTTTTTTTTTTAAAAUHHHHHHHHHHHNNNNNNNNNB
    \\HHHHHHHHHHHHRHRAAAAAAAAAAXEEEEEEEEEEESDGGGGIIIIIUUUUUUVVVVVVVVIIJJPIPIIYYYYYYYYYYYXXXXXXXXXXSSSSEEECCCCCCCFTTTTTTTAAAAUHHHHHHHHHHHHNNNNNNNNN
    \\HHHHHHHHHHHRRRRRRAAAAAAAAEEEEEEEEESSSSDDSGGGIIIIGUULLUVVVVVVVVIIJPPIIIYYYYYYYYYYSSSSXXXXXXSSSSSSEEEEECCCCCCDTTTTUAAAAAHHHHHHHHHHHHHNMNNNNNNK
    \\HHHHHHHHHRRRRRRRRRAAAAAAAEEEEEESESSSSSSSSGGGIIGGGGGLLLVVVVVJMIIIIIIIIIYYYYYYYYYYSSSXXXSXSXXXSSSEEEEEECCCCTTTTTTTUAAAAJHHHHHHHHHHHHHMMTNNNNNN
    \\HHHHHHHHHRRRRRRARRAYYYKKAKEEEEESSSSSSSSSSSSGGGGGGGGGLLLLVJVJMIIIIIIIIIYYYYYYYYYSSSSSSSSSSSEESSEFEEEECCCCCZTTTTTTTAAAAJJHHHHHHHHMHMMMMMMNUNNU
    \\HHHHHHHHHRRRRRAARRAAAYKKKKKEEEKKSSSSSSSSSSGGGGGGGGGGLLLLLJJJMIIIIIIIIIIIIMYRYYYSSSSSSSSSSSEEEEEEEEEEECCCLLTTCCCCCDDAAJHHHHHHHHMMMMMMMMMMUUUU
    \\HHHHHHHHHRRAAAAARRAAAKKKKKKKKKKKKKSSSSKSSGGGGGGGGGGGLLLLJJJDDIDDDHDIIIIIIYYYYYSSSSSSSSSSSSSEEEEEEEEEEECELLLLCCCCCDDABHHHHHHHHIIMMMMMMMMMMMUU
    \\HHHHHHHHHRRAAAAAAAAAAAKKKAKKKKKKKKKSSKKGGGGGGGGGGGGGLLLLLJJDDDDDDDDIIIIHHYYYSSSSSSSSSSSSSSSSSEEEEEEEEEEELLLLCCCCCDDBBBBHHHIIIIMMMMMMMMMMMUUU
    \\HOHOHHHHRRAAAAAAAAAAAAKAAAKKKKKKKKKKKKKKKGGGGGGGGGGGGLLLDJDDDDDDDDDDIHHHHHSSSSZSSSSSSSSSSSSSSEEEEEEEEEELLLLLLCCZCDDBBBBBHHIIIIMMMMMMMMMMMUUU
    \\ROOOOHTHRRRAAAAAAAAAAAAAAKKKKKKKKKKKKKKKKGGGGGGGGGGGGGGDDJDDDDDDDDDHHHHHHHZZZSZZSSSSSSSSSSSSSOEEEEEEEEEELLLLLCBUDDDBIIIBHHHIIIMMMMMMMMMMMMUU
    \\ROORRTTHRRAAAAAAAAAAAAAAAKKKKKKKKKKKKKKKKBGGGGGGGSGGGGGDDJDDDDDDDDDDDDHHZZZZZZZZSSSSSSSSSSSSOOEEEUUUUULLLLLLLLBUUDDDDIIIIHIIIIMMMMMVMMMAAAIU
    \\RRRRRTTRRRAAANNAAAAAAAANNKKKNKKKKKKKKKKKBBGGGGGGGGQGGGGGDEDDDDDDDDDDDDDZZZZZZZZZZZISSSSSSSSSOOOEEUUUUUUULLLLLUUUUUDIIIIIIIIIIIMITMCMMMMAAIIU
    \\RRRRRRTRRROOAAAAAAAAAAAANNNNNNKKKKKKKKKKKBBBGBGGGGQGGGGDDDDDDDDDDDDDDDDZZZZZZZZZZZISSSSSSSSSOOOTTUUUUUUUULLLLUUUUIIIIIIIIIIIIIMIICCCMMMIIIII
    \\RRRRRRRRRRRRREEAAAAAAAAANNNNNNKKMMMMKKKKKKBBBBBBBGGGGGGDDDDDDDDDDDDDDDDDZZZZZZZZPZIISSSSSSOOOOOTTTUUUUUUUULULUUUUUUIIIIIIIIIIIIIIIICMCMIIIII
    \\RRRRRRRRREEEEEEEAAAAAAAAANNNNNNKKMMMKKKKBBBBBBBBGGGGGGGGDGDDDJDDDDDDDDUZZZZZZZZZIIIIIIIIOOOOOOOTTTUUUUUAUUUUUUUUUUNIIIIIIIIIIIIIICCCCCIIIIII
    \\RRRRRRRREEEEEEEEAAPAAAAAAANNNNNMMRRMMKKBBBBBBBBBGGGGGGGGGGDDJJJJDDDDDDDQZZZOOZZOOIIIIIIIOOOOOOOOTTUUUMUAAAAUUUUUUUUIIIIIIIIIIIIICCCCIIIIIIII
    \\RRRRRRRRREEEEEEEEAAAAAAKANNNNNLMMMMMMKKBBBBBBBBBGGGGGYGGGGGGGJJJJJJJDDDEZZOOOOOOIIIIIIIJOOOOOOOTTTBHBBBBBBAAIIUUDDIIIIIIIIIIIIIICCCCCIIIAAII
    \\RRRRRRREEEEEEEEEEEEAAAAANNNNNNNMMMMMMBBBBBBBBBBBBBGGGYYYGGGJGJJJJJJJDJDEZZOOOOIIIIIIIIIJJOOOOOOOTBBHBBBBBBYYIIIBBDDDDIIIIIIIIIIIICCCCIIIIAIA
    \\RRRRRRREEEEEEEEEEEEEAEAAENNNNNNNMMMMMMBMBBBBBBGBGGGGYYYYGGGJJJJJJJJJJJJEEEEOOOIIIIIIIIIJJJOOJKOPBBBBBBBBBYYYIIIDDDDDDIDDIIIIIIIIDWWWWWAAAAAA
    \\RRRRRRREEEEEEEEEEEEEEEAEEEEENNNNMMMMMMMMBBBBBBGGGYYYYYYYYGGGJJJJJJJJJJUEEEEOOIIIIIIIIIIJJJJJJKKBBBBBBBBBBVVVVIIIDDDDDDDDDIIIIIWWWWWWWWAAAAAA
    \\RRRRRRRIIEEIEEEECEEECEEEEENNNNNNMMMMMMMMMMBBGGGGGGYYYYYYGGGGJJJJJJJJJJJEEEEOOIIIIIIIIIIIJJKKKKKKKGBBBBBIPIVVVIIIIDDDDDDDDDDIIWWWWWWWWAAAAAAJ
    \\RRRRRRRIIEIIEEEECCECCCEEEEEENNMMMMMMMMMMMMGBBGGGGGYYYYYYYGJJJJJJJJJJJJEEEEEIIIIIIIIIIIIIJKKPKKKKKKBBBBBIIIIIIIIIIIDDDDDDDDDIWWOWWWWWWAAAAAAA
    \\RRRRRRRIIIIIEEECCCCCCCEEEEEMMMMMMMMMMMMMRRGGGGGGGGYYYYYYYYYJJJJJJJJJJJEEEEEEIIIIIIIIIIIIKKKKKKKKKKKKBBBIIIIIIIIIDDDDDDDDDDDDOOOOWWWWWWAAAAAA
    \\RRRRREEEEIIIEEECCCCCCCCEEEMMMMMMMMMMHMMMRRRGGGGGGGYYYYYYYYYUYYJJJJJJEEEEEEEEEEEIIIJIIIIKKKKKKKKKKKKKFBFIIIIIIIIIDDDDDDDOODOOOOOOWWWWWWAAAAAA
    \\IIIIIEEEEEEEEEECCCCCCCCCCEEMMMMMMMHHHHHRRRRGGGGGGGYYYYYYYYYYYYYIJJJJEEEEEEEEEEEIIJJIIIKKKKKKKKKKKKKKFFFIIIIIIIIIDIIDDDDOOOOOOOOIOWWWWAAAAAAA
    \\IIIIIEEEEEEEEECCCCCCCCCCCERMMMMMMMMHHRRRRRGGGGSGGGYYYYYYYYYYYYIIJJJEEEEEEEEEEEEEJJJIOOHHKKKKKKKKKKKKKPFFIIIIIIIIIIIDDDOOOOOOOOOOOWWWWAAAAAAA
    \\IIIIIEEEEEEEEECCCCCCCCCCCCCMMMMMMMHHHRRRRRGGIISSSGYYYYYYYYYYYJJJJJJEEEEEEEEEEEEEJJBBOOHKKKKKKKKKKKKKPPFFIIIIIIIISIIIDDIIOOOOOOOOOOWWWWWAAAAA
    \\IIIIIEEEEEEEEECCCCCCCCCCCCCMMMMMMHHHHRRRRRGHIISSSSYYYYYYYYYYYJVJPJJJEEEEEEEEEELBBBBOOOHKHHKKKKKKKKKKKPBFFIIIIIIISIIIIIIOOHOOOOOOOOWWWWWAAAAA
    \\IIIIIEEEEEEEEQQCCCCCCCCCCCMMMMMMMHHHHHHRRHHHIIIISSYYYYYSSYYYYMPPPPPPPEEEEEEEEEBBBBBOHHHHHHHKKKKKKKKKOPPPPDDSIISSSIIIIIIHHHOOOOOOOOOWWWWWWAAW
    \\NIIIIEEEEEEEEEQQCCCCCCCCCMMMMMMMMHHHHHHHHHHHHIIISSYSSYYSSSYYYMPPPPPPPPEEEEEEEEBBBBBOHHHHHHHHKKKKEEEKKPPDDDDSISEESSSIIIIHHHHHOOOOOOOWWWWWWWWW
    \\IIIDSSQIQQQQEEEQCCCCCCCSSSMMMMMHHHHHHHHHHHHHHIIISSSSSYSSSSSSYYPPPPPPPPEEEEEEBBBBBBBHHHHHHHHHHKKKEEEKKCPPDPDSSSSSSSSIIIHHHHHHHOOOOQOWWWWWWWWW
    \\DDDDDSQQQQQQQEQQCQQCCCXSSSMMMSHHHHHHHHHHHHHHHIIISSSSSSSSSSSSSPPPPPPPPPPEEEEEEBBBBBBHHHHHHHHHHKKKKEPPGPPPPPSSSSSSSSSIHHHHHHHHOOOOOOOWWWWWWWWN
    \\DDDDDSSQQQQQQQQQQQFFFSSSSFMMSSSSSHHHHHHHHHHHBSSSSSSSSSSSSSSSSYYPTPLPPPPEEEEBEBBOBBBHHHHHHHHHHHHPPPPPPPPPPPSSSSSSSSSSCCHHHHHHOOOOOOOWWWWWWNNN
    \\DDDDDSSSQQQQQQQQQQFFFFSSSSSSSSSSSSHHHHHHHHHHHSSSSSSSSSSSSSSSSSDDDPPPPPPEEEEEUUBBBBBHHHHHHHHRHHHHPPPPPPPPPPSSSSSSSSSSHHHHHHHHHOOOONOWWWWWWWNN
    \\SSDDDSSSQQQQQQFFQFFFFFSSSSSSSSSSSHHHHHHHHHHMMSSSSSSSSSSSSSSSSPDDDZPPPPPEEEEZUZRRBBHHHHHHHHHRRHHPPPPPPPPPPPRSSSSSSSSSHHJHHHHGGGGGGWWWWWWWWNNN
    \\SSSSDSSSSSSQQQFFFFFFFFFSSSSSSSSSSSHHHHHHHBHMMMMASSSSSSSSSSSSSDDDDDZPPPZEEEEZZZZREEEEHHHHHRRRRHHHMPPPPPPPPPRPPSSSSSSDDDHHHHHGGGGGGGWWWNNNWNNX
    \\SSSSSSSSSSSQQQSSFFFFFFFFKFFSSSSSSSSHHHHHBBBBMMMMNSSSSSSSSSSSDDZZDZZPZZZEEEZZZZRRREEEHEHHRRRRRRRRRRPPPPPPPPRPPSSSSSSDDDDHDHGGGGGGGWWWNNNNONNX
    \\SSSSSSSSSSSSSSSCFFFFFFFFFFFSSSSSSYYYYHHHHZBBBKKKSSSSSSSSSRSSZZZZZZZZZZZZZZZZZZRREEEEEEHNNRRRRRRRRPPPPPPPPPPPPPPPZSSDDDDDDDDGDLZGGGWNNNNNNNNN
    \\SSSSSSSSSSSSSSSCFFFFFFFFFFFFFSSSSYYYYHHHKBBBBKKKCSCSSSSSSRZZZZZZZZZZZZZZZZZZZZZEEEEEEEENNRKRRRRRRRRPPPPPPPPPPDPDSSDDDDDDDDDDDZZGGGGGNNNNNNNN
    \\XSSSSSSSSSQQQSSSSFFFFFFFFFFFFSSSSYYYYYYKKKEEEERCCCCSSSSSSRZZZZZZZZZZZZZZZZZSUZZZZEEEEEENEERRRRRRRRPPPPPPPPPPPDDDDDDDDDDDDDDDDZZGZZGGGNNNNNNN
    \\SSSSSSXSQQQQQSQFFFFFFFFFFFFSSSSSTTTTYYYYEEEEEERCCCCCSSSSSSZZZZZZZZZZZZZZZZZSUUUSZEEEEEEEERRRRRRRRPPPPPPPPPPPDDDDDDDDDDDDDDDDZZZZZZZGGNNNNNNN
    \\XSSXXXXQQQQQKSQQQFFFFFFFFFWCOSSTTTTTYYYYYYYYEEECCCCCOSSSSZZNZZZZZZZZZZZZSSSSSSSSEEEEEEEEERRRMMRRRPPRPPPPPPFDDDDDDDDDDDDDDDDDVZZZZZZGGGNNNNNN
    \\XXXXXXXXQQQQQQQQQFFFFFFFFFWCCCCCTTTTYYYYYYYYCRRCCCCKOSOOSNNNZZZZZZZZZZZZZSSSSSSSSEMMMEEEEMMMMMRRRRRRRPPPFPFDDDDDDDDDDDDDDDGGZZZZZZGGGGGGGNGG
    \\XXXXXXXQQQQQQQQQQQFFZZZZZZZZZZHHTTTTTTYYYYYYCCCCCCOOOOOOOINNZZZZZZZZZZZZZSSSSSZZZZMMMMEEEMMMMMRRRRRRRPRRFFFFJJJJJDDDDDDDDGGZZZZZGGGGGGGGGGGG
    \\XXXXXQQQQQQQQQQQQQFFZZZZZZZZZZZZZZZZTTYYYYYYCCCCCOOOOOOOOINZZZRRRRZRRZZZSSSSSSSZZZZMMMMMMMMMMMMRRRRRRRRRRRLLMJJJJJDDDDDDDDGGGZGGGGGGGGGGGGGG
    \\XXXXXQQRQQQQQQQQQQFFZZZZZZZZZZZZZZZZYYYYYYYYCCCCCCOOOOOOOOXZRRRJRRRRRZZSSSSSSSSZZZZMMMMMMMMMMMMRRRRRRRRRRRLLJJJJJJJDJJDDDDGGGGGGGGGGGGGGGGGG
    \\XXXXXXXQQQQQQQQQQQFFZZZZZZZZZZZZZZZZYYYYYYYYCCCLLOOOOOOOOOXXRRRRRRRRSZSSSSSSSSSYZZZZMMMMMMMMMMMMRRRRRRRRLLLLJJJJJJJJJJDDDGGGGGGGGGGGGGGGGGGG
    \\XXXXXXQQQQQQQQQQQQQFZZZZZZZZZZZZZZZZYYYYYYYYCLCLLOOOOOOOOOOORRRRRRRRSZSSSSSSSSSYYYZZMMMMMMMMMMMMMRRRRRWRLLLDJJJJJJJJJJJJGGGGGGGGQGGGGGGGGGGG
    \\XXXXXXQQQQQQQQQQQQQFZZZZZZZZZZZZZZZZYYYYYYYYCLLLLLLLOOOOOOOORRRRRRRRSZSSSSSSSYYQYYYZMMMMMMMMMMMMMRRRRRRLLLLJJJJJJJJJJJJJGGGGGGGGQQGGGGGGGGGG
    \\XXXXXXQQQQQQQQQQQQQFFFQQQQQQQZZZZZZZTYYYYYYYLLLLLLAAOOOOOKOOORRRRRRRSSSSSSSYYYYYYYYYYLLLMMMMMMMMRRRRRRRLLLLLJJJJJJJJJJGGGGGGGGGGQAGGGGGGGGGG
    \\XXXXXXQQQQQQQQQQQQQFFFQQEQQQQZZZZZZZTTTTTNTPLLLLALAOOOOOOOOOORRRRRIPSSYRSIYYYYYYYYYYYLYMMMMMMRMPRGGRRRLLLLLLJJJJJJJJJJGGGGGGGGGQQQGGGGGGGGGG
    \\XXXXXXQQQQQQQQQQQQQQEEEEEQZZQZZZZZZZZTTTTTTTAALAAAAOOOOOOOOOOXXRRIIPSSYYSYYYYYYYYYYLYYYYYPMMMMMPRGRRRRRRLLLLLJJJJJJJJJGGGQQGQQGGQQGGGGGGGGGG
    \\XXXXXXXQQQQQQQQQQQQQQQQEEQZZZZZZZZZZTTTTTTTTTAAAAAAOOOOOOOOXXXXXIIIIYYYYCYYYYYYYYYYYYYYYPPPPMPPPPPRRRGRLLLLLLLVJJVJJJGGGGQQGQQQQQQAQGGGGGGGG
    \\XXXCXXXXXQQQQQQQQQQQQQRREZZZZZZZZZZZTTTTTTTTTTAAAAAAAOOOOXXXXXXXIIIIYYYYYYYYYYYYYYYYYYYPPPPPMMPPPRRRGGGLLLVVLVVJJVJJJGQQQQQQQQQQQQQQQGGGGGGG
    \\CCCCCCXXXQQQQYQQQQQQQBROOOOOOZZZZZZTTTTTTTTTTTTTAKAAOOOOOXXXXXXXIIIYYYYYTTYYYYYYYYYYYYYYPPPPMPPPPRRRPGGGVVVVVVVVVVVVQQQQQQQQQQQQQQQQQGGGGGGG
    \\CCCCCCCXXYQQYYBBQQQQBBROOOOOOZZZZZTTTTTTTTTTTTEKKKKKKOXXXXXXXXXXIIIYYYTYTTYYYYYYYYYYYYPPPPPPMPPPPPPPPPGGVVVVVVVVVVVVNNQQMQQQQQQQQQQQQGGGGGGG
    \\CCCCCCCXYYYYYYBBQQBBBBOOOOOOOZZZZTTTTTTTTTTTTKKKKKKKKKXXXXXXXXXXIIITTTTTTTYYYYYYYAYYYAPPPPPPPPPPPPPPPGGGVVVVVVVVVVNNNQQQMQQQQQQQQAQQGGGGCGGG
    \\CCCCCYYYYYYYYYBBBBBBBBOOOOOOOZZZZTTTDFTTTTTTTTKKKKKKKKKXXXXXXXXXIITTTTFTTTTYYYYYYAAAYAAAAPPPPPPPPPPPPGGGGVVVVVVVVVNNNMMMMMMQMQQQQQVVVVVGCGGG
    \\CCCCCXYYYYYYYYBBBBBBBBOOOOOOOZZZZZZTDDDTTTTTKKKKKKKKKKKXXXXXXXXXXXXTTTFFFYYYCYYYAAAAAAAAAPPPPPPPTTTTRRRGGVVVVVVVVVVVNNNMMMMMMMRRRRRVNVVGCCCC
    \\CCCCCCUYYYYYYYYBBBBBBBOOOOOOOOOOZZZDDDDDTTTTKKKKKKKKKKKXXXXXXXXXXXXTTTFFFFFFFTYYAAAAAAAAAAPPPPPTTTXRRRRBBBVVVVVVVVVNNNMMMMMMMMMRRRRVVVVCCCCC
    \\CCCCCCCYYYYYYYYYYZBBBBBBOOOOOOOOOZZZDDITTTTTKKKKKKKKKKXXXXXKKXXXXXXTFFFFFFFFFYYAAAAAAAAAASPPPPPTTTTTTAABBPVVVVVVVOVVMNVMMMMMMRMRRVVVVVVCCCCC
    \\CCCCCCCCYYYYYYYTTTTBSBOOOOOOOOFOZZZDDDDTTTTKKKKKKKKKKKKKXXXKKKKXXXXTFFBFFFFFFFFAAAAAAAAAAAPPPTTTTTTTTBBBBBBVVVVVVVVPMMMMMMMMRRRRRVVCVVVVVCCC
    \\CCCZZCCYYYYYYYTTTTTTTFOOOOOOOOOZZZZDDDDTTTHHHKKKKKKKKKKKXXXXXKXXXXTTFBBFFFFFFAAAAAAAAAAAAAAAJJJJTJJJBBBBBPVVVVVPPVPPMMMMMMMMRRRRRYYCCVVVVCCC
    \\CCCZZZZZZZYYYTTTTTTTTOOOOOOOOOOOOZZZZZZZZHHHHKKKKKKKKKKKXXXKKKXXKKTTTTQQQQFFCAAAAAAAAAAAAAAJJJJJTJJJBBBBBPPPPPPPPPPPMMMMMMMMMRMMMYYCCCCCCCCC
    \\CCCCZZZZZYYZYTTTTTTTTOOPOOOLOOOZZZZZHHHHHHHHKKKKKKKKKKKKXXKKKKOOKETTTGQQQQCCCCVAAAZAAAAAAAAAAAJJJJJBBBBBPPPPPPPPPPPPMMMMMMMMMMMMMYYYYYYCCCCC
    \\CZCZZZZZZYYZZZZTTTTTTTOODOOTTDZZZZZZDHHHHHHHHKKHHKKKKKXXXKKKKKKKKKKKSKKQQQCCCCCCAFAAAAAQAQQQAJJJJJJJBPBPPPPPPPPPPPPPPPMMMMMMMMMBBRYYYYCCCCCC
    \\ZZZZZZZZZZZZZZTTTTTTTTOOOOOTTDDDDDDZDDHHHHHHHHHHHKKKKKKKKKKKKKKKKKKKKYKQCCCCCCCCCCCVAAOQVQQQQJJJPPPPPPPPPPPPPPPPPPPPPPMMMMMMMBBBBYYYCCCCCCCC
    \\ZZZZZZZZZZZZZZZTTTTTTTTOTTTTTDDDDDDDDDDDHHHHHHHHHKKKKKBKKKKKKKKKKKKKKKKCCCCCCCCCCCVVAQQQQQQQQJJJPJJJPPPPPPPPPPPPPPPPPPMMMMMBBBBBBBBBCCCCCCCC
    \\ZZZZZZZZZZZZZZZTTTTTTTTTTTTDDDDDDDDDDDDDHHHHHHHHHHKKKBBBBKKKKKKKKKKKKKKCFCCCCCCCCCCVAUQQQQQJJJJJJJJJPPPPPPPPPPPPPPPPPPPPMMBBBBBBBBCCCCCCCCCC
;
